### PR TITLE
Combine two weapons.Register ents loops

### PR DESCRIPTION
**Pull request by Kefta**

### CODE REVIEW

**Comment by willox** [comment]
What's the benefit?

**Comment by Kefta** [comment]
Less overhead in the chance weapons.Register is called during actual playtime. I personally do this to hotswap CS:S weapons in maps that have them for comparison

**Comment by GitSparTV** [comment]
Bump, this should increase loading time (very little, but this PR doesn't break anything)

**Comment by robotboy655** [comment]
Doubt it will do anything for loading times, but I guess it doesn't hurt either.

**Pull request merged**
