### PR TITLE
Add timer.Loop

### PR DESCRIPTION
**Pull request by Dragoteryx**
`timer.Loop(number delay, function func)` will call the function passed as a parameter every delay second until the function returns false or nil. You can also return a number along with the boolean to change the delay.
```lua
-- prints numbers from 10 to 0 at a faster and faster rate
local value = 10
timer.Loop(10, function()
    print(value)
    value = value - 1
    return value >= 0, value
end)
```

### CODE REVIEW

**Comment by robotboy655** [comment]
timer.create with reps set to 0.

**Comment by Kefta** [comment]
@robotboy655 That isn't anonymous - it requires giving the timer a name.

**Comment by mcNuggets1** [comment]
This function would actually be pretty cool.

**Comment by thegrb93** [comment]
You can do the same thing with timer.Simple alone.

**Pull request closed without merging**
