### PR TITLE
Fix weapon_medkit holstered healing regression

### PR DESCRIPTION
**Pull request by Kefta**
Calculate the health to regen on Deploy/Think.

### CODE REVIEW

**Comment by Kefta** [comment]
A Should/CanTakeDamage binding would be useful here to avoid using GetInternalVariable in the codebase

**Comment by robotboy655** [comment]
I think it would be better to save holder time, and calculate and add how much should've regen'd between that time and the deploy function. Should result in better looking code as well.

**Comment by Kefta** [comment]
I thought of that, but if any addons wanted to display the current ammo of the medkit on the HUD while holstered, like for a dedicated healer class, then this would keep it accurately updated. This could be left for SWEP override territory instead though.

**Comment by Kefta** [comment]
New solution to be tested tomorrow.

**Comment by Kefta** [comment]
Good to go from my testing. Only prediction error is from the SetHealth call but there seems to be something funky happening with that function in particular during prediction.

**Comment by brandonsturgeon** [comment]
LGTM 👍
I'll apply this PR to our Build/Kill server and let you know if we see any problems.

**Comment by brandonsturgeon** [comment]
Running it for about half a day, everything seems good 👍

**Comment by T-Rizzle12** [comment]
Any ETA when this would be released?

**Review by robotboy655 — APPROVED** [review]

**Pull request merged**
