### PR TITLE
Make ent:GetPlayer() work after rejoins

### PR DESCRIPTION
**Pull request by Lexicality**
I've found myself doing this in every entity I make, and it would be a lot more convenient for the game to do it for me.

### CODE REVIEW

**Comment by mcNuggets1** [comment]
If a player reconnects are their previous props assigned to this player?

**Comment by Lexicality** [comment]
What do you mean by assigned?

**Comment by mcNuggets1** [comment]
Conflicts

**Comment by Lexicality** [comment]
Rebased off master

**Pull request merged**
