### PR TITLE
 Utilize The close method in various places and add removeing option

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by GitSparTV** [comment]
If you are not good at git CLI, use GitHub Desktop or Sublime Merge (or any other GUI-based git client)

**Comment by GitSparTV** [comment]
You can mark it as draft on this page, somewhere at the top or in `...` menu

**Comment by dvdvideo1234** [comment]
Hello, @Rubat, @GitSparTV 

I do not intend to add anything else to this, so you are welcome to merge it when needed.

**Review by robotboy655 — APPROVED** [review]

**Comment by Aws0mee** [comment]
removeing

**Pull request merged**
