### PR TITLE
Create table.IsEmpty

### PR DESCRIPTION
**Pull request by WilliamVenner**
Quickly returns whether a table has iterable items in it - useful for checking whether non-sequential tables are empty.

### CODE REVIEW

**Comment by Kefta** [comment]
This would be more efficiently implemented as ``return next( tbl ) == nil``

**Comment by thegrb93** [comment]
lol anyone worth their salt will just do if next(t) then or if not next(t) then

**Comment by AMD-NICK** [comment]
`if not next(t) then` looks better for me

**Comment by Kefta** [comment]
> `if not next(t) then` looks better for me

What if ``next`` returned false?

**Comment by thegrb93** [comment]
If you're using bool for your table keys then I imagine you wouldn't need to check if its empty. And if you did, you wouldn't need next.

**Comment by AMD-NICK** [comment]
> > `if not next(t) then` looks better for me
> 
> What if `next` returned false?

in a case when it's possible I'll use more accurate comparison

**Pull request merged**
