### PR TITLE
Better duck animation response.

### PR DESCRIPTION
**Pull request by ZehMatt**
The player would only go into the crouch animation once fully crouched. It will be now active as soon the player has IN_DUCK set.

Original: http://share.epic-domain.com/2016-08-15_13-29-50.webm
Improved: http://share.epic-domain.com/2016-08-15_13-28-52.webm

### CODE REVIEW

**Comment by Kefta** [comment]
You should also change that Length2D to Sqr since it's by a constant.

**Comment by ZehM4tt** [comment]
Thanks, done as suggested.

**Comment by mcNuggets1** [comment]
That is something that always haunted me in my dreams.
Thank you for fixing it!

**Comment by mcNuggets1** [comment]
Already forgotten?

**Comment by willox** [comment]
Not forgotten, but this requires more work than just a little Lua because key-down states don't get networked to other players.

**Comment by Kefta** [comment]
It's nice to have this feedback on why PRs aren't merged, though

**Comment by willox** [comment]
I don't merge any PRs because I don't want to deal with any issues they cause

**Comment by Kefta** [comment]
I mean on potential issues and more depth on the subject, like you explained briefly above

**Comment by mcNuggets1** [comment]
Well it was too good to be true.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/1116#issuecomment-382703449

**Pull request closed without merging**
