### PR TITLE
fix typos and other runtime errors

### PR DESCRIPTION
**Pull request by CapsAdmin**
remove unused variables
fix some cases of unintended global lookups and assignments

these were found by using luacheck

### CODE REVIEW

**Comment by mcNuggets1** [comment]
Awesome work, dude.

**Comment by robotboy655** [comment]
This will take 300 years to review, can you split similar changes to separate PRs?

**Comment by CapsAdmin** [comment]
I'm not really sure how I should do that in a way that makes it not take 300 years to review.

**Comment by Kefta** [comment]
Could you change weapon_fists to use the local instead? Would be better than calling CurTime three times. Would also help if you did the same for the Deploy (CurTime() + vm:SequenceDuration() / speed as a whole) and PrimaryAttack functions as well.

**Comment by CapsAdmin** [comment]
I've given this some thought and I think I know how to go about doing it.

**Pull request closed without merging**
