### PR TITLE
Be nicer to people with smaller servers

### PR DESCRIPTION
**Pull request by Leystryku**

### CODE REVIEW

**Comment by BlackCetha** [comment]
Have a look at #1441

**Comment by Leystryku** [comment]
Playercount playing a role is nice, however, currently you need 16 players
to get your server listed high. With this its 8 which allows smaller
communities to become bigger, faster

BlackCetha <notifications@github.com> schrieb am So., 18. März 2018, 14:38:

**Comment by Kefta** [comment]
I think it would be better for the playercount's effect to work as a decaying function instead of having arbitrary cutoffs.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/commit/9b99f9ea1a2d5a4c78fbde9b786910aa2b36fefe

**Pull request closed without merging**
