### PR TITLE
Add table.Compare

### PR DESCRIPTION
**Pull request by Kapppa**
Will allow you to tell if two tables have the same values in the same key

### CODE REVIEW

**Comment by thegrb93** [comment]
I stared at this for two minutes trying to make sense of it. Why

**Comment by Kefta** [comment]
Why do you need to copy all values to new tables? Also, the ``#`` operation is not defined for non-sequential tables - you could have two "equal" tables that return different len results.

**Comment by 11Lee1** [comment]
couldn't you do something like this
`function table.Compare(tab1,tab2)
	for k,v in pairs(tab1) do
		if(tab2[k] == nil || tab2[k] != v)then
			return false;
		end
	end
	return true;
end`

**Comment by Kefta** [comment]
@11Lee1 The ``== nil`` check is necessary since a non-nil value will never be equal to nil. Also, you'll need to also loop through tbl2 since your implementation will consider ``{1, 2, 3}`` equivalent to ``{1, 2, 3, 4, 5}``.

**Comment by Grocel** [comment]
The keys can also be a tables, so you need would check those to be equal as well.

**Pull request closed without merging**
