### PR TITLE
Change pairs to ipairs

### PR DESCRIPTION
**Pull request by ceifa**
A micro optimization to save some nanosecs of cpu

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
It's better but not faster as it will not jit compile and outside or jit compiled mode, pairs is faster than ipairs

**Comment by Kefta** [comment]
This will be faster in x86_64's JIT.

**Comment by ceifa** [comment]
> It's better but not faster as it will not jit compile and outside or jit compiled mode, pairs is faster than ipairs

Didn't know that, does it have a reason to jit compile pairs but not ipairs?

**Comment by GitSparTV** [comment]
It wouldn't compile in both cases.
But pairs **apprently** is faster in non-JITted code.
The possible reason is the implementation, I didn't look deeper but I assume this.

**Comment by JarosLucky** [comment]
#1609

**Comment by robotboy655** [comment]
Superseded by https://github.com/Facepunch/garrysmod/pull/1609

**Pull request closed without merging**
