### PR TITLE
Expand File object

### PR DESCRIPTION
**Pull request by edgarasf123**
Added File methods with unsigned support, in addition added aliases to existing methods that make more sense.

### CODE REVIEW

**Comment by Kefta** [comment]
This should be done in the engine imo - maybe add methods to write ints/uints of arbitrary bit counts?

**Comment by Kefta** [comment]
Maybe that would be more appropriate for a bit stream, but the methods in this PR should still be implemented internally imo

**Comment by edgarasf123** [comment]
I made s request to implement unsigned number support a month ago (https://github.com/Facepunch/garrysmod-requests/issues/1059). Its now getting buried among other 500 requests. Its more likely to get pull request accepted, than someone implementing it on C.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/1059

**Pull request closed without merging**
