### PR TITLE
Add a casing style parameter to AccessorFunc()

### PR DESCRIPTION
**Pull request by TomDotBat**
This adds a new parameter to `AccessorFunc` which makes it possible to change the casing style by passing a `CASING_` enum.
The casing styles I have added are:
- PascalCase
- camelCase
- snake_case
- UPPER_SNAKE_CASE

This will be extremely helpful to people who don't want to use PascalCase on their table methods. To ensure compatibility isn't broken, PascalCase will be the default option when the casing parameter isn't populated.

### CODE REVIEW

**Comment by garryspins** [comment]
All mah homies love UPPER_SNAKE_CASE

**Comment by ChrisWongUK** [comment]
ButPascalsCase IsReallyEpic

**Comment by GitSparTV** [comment]
Gmod uses this function for its own styling

**Comment by thekillertoaster** [comment]
PascalCase is the way to go

**Pull request closed without merging**
