### PR TITLE
Ported CCollisionProperty::IsPointInBounds to util.IsPointInBounds

### PR DESCRIPTION
**Pull request by ForrestMarkX**
Ported over CCollisionProperty::IsPointInBounds to be a utility function for convenience, I'm unsure if this acts exact to how the C++ version works but should be pretty close

### CODE REVIEW

**Comment by bmwalters** [comment]
You got an unrelated change in here somehow

**Comment by ForrestMarkX** [comment]
Yeah I see it, lemme fix that

**Comment by bmwalters** [comment]
For the future, if you wanted to do it without the revert commit (but rewriting history in the process):
```
git reset --hard HEAD^
git push -f
```

**Comment by ForrestMarkX** [comment]
Ohh interesting, good to know

**Comment by ForrestMarkX** [comment]
Closing it for now since

**Comment by bmwalters** [comment]
You have to do it one more time. The first time you did it, it destroyed the "revert" commit.

**Comment by ForrestMarkX** [comment]
Ohh I see, thank you. Sorry I'm having trouble with this. Never done pull requests before

**Comment by Kefta** [comment]
You don't have to change it now, but in the future, m_ in front of a variable means member variable, which should be used if it's part of a class, or in Lua, (meta)tables or userdata. In this case, your variables are all local as the OBB accessors don't return direct references to the player variables, and should not contain the member prefix.

**Comment by GitSparTV** [comment]
if it uses an entity, maybe it has sense to add it to Entity metatable?

**Comment by robotboy655** [comment]
Will be added as `Entity:IsPointInBounds`

**Pull request closed without merging**
