### PR TITLE
Be able to hide the tool menu in the context menu

### PR DESCRIPTION
**Pull request by MoskalykA**
Hi there,
I suggest not displaying the tool menu in the context menu.
This functionality was already planned but I need it.

### CODE REVIEW

**Comment by Zaurzo** [comment]
This is going to make it not show up at all if nothing is returned in the hook. Default it to true, and set it to false if ContextMenuShowTool returns false.

```
local bShouldShow = true

if ( hook.Run( "ContextMenuShowTool" ) == false then )
    bShouldShow = false
end
```

**Comment by Kefta** [comment]
You can condense the above code into a single line by moving the hook call to the variable declaration

**Comment by MoskalykA** [comment]
👍🏻

**Review by robotboy655 — APPROVED** [review]

**Review by Be1zebub — COMMENTED** [review]
all you need is just `local bShouldShow = hook.Run( "ContextMenuShowTool" ) ~= false`

**Pull request merged**
