### PR TITLE
Fix table.Add infinite loop

### PR DESCRIPTION
**Pull request by zohart75**
Calling table.Add with the same tables will freeze the game forever.

### CODE REVIEW

**Comment by Aws0mee** [comment]
I'm not sure what specific case you would want this for, but I think it would be best to just implement it in your code.
For example:

```lua
if table1 ~= table 2 then
    table.Add(table1, table2)
end
```

I don't think it makes sense to add this check to the function since this won't be a problem in most circumstances.

**Comment by Kefta** [comment]
The function should have protection from stalling the game no matter what arguments are passed. It's a library function. I would even support an error being thrown so developers can catch their logic mistake more easily.

**Comment by garryspins** [comment]
Its a free check, +1

**Review by robotboy655 — APPROVED** [review]

**Comment by robotboy655** [comment]
I couldn't reproduce an infinite loop, but it does hang the game for a bit.

**Comment by zohart75** [comment]
Idk why, but my srcds just stopped responding lol

**Comment by zohart75** [comment]
UPD: Lua throws an error when trying to table.insert for more than max table key limit.

**Pull request merged**
