### PR TITLE
Default the color creation to white when no arguments are provided

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
These will produce the same result:
```lua
local c = Color(1,2,3,4)

Color(1,2,3,4)
Color(c)
Color({1,2,3,4})
```

**Comment by Kefta** [comment]
I do not see the convinence of the default args, especially with an already-present color_white const, and the constructor additions have been done more efficiently and cohesively here: https://github.com/Facepunch/garrysmod/pull/1312

**Comment by dvdvideo1234** [comment]
@Kefta 

What should the 2-nd, 3-rd and 4-th option return then ?

**Comment by Kefta** [comment]
The 4th already defaults to 255, the 1st thru 3rd should not be optional.

**Comment by GitSparTV** [comment]
Can we just have a separate function for this? Color function is already called many times

**Comment by dvdvideo1234** [comment]
@GitSparTV  The idea is to be able to be called like `Vector()` and defaulting to `255` will not change anything as right now everyone calls it with `Color(0,0,0)` for example by providing at least 3 arguments.

**Comment by Kefta** [comment]
Vector() works as a single constructor because it's a C func which can handle multiple Lua types. Adding this same functionality to Color in Lua is going to significantly slow the func down.

**Comment by dvdvideo1234** [comment]
@Kefta Will wait for the other patch implementation then. Will be nice to have `Color()` ;)

**Comment by thegrb93** [comment]
color_white >:v

**Comment by ExtReMLapin** [comment]
racist

**Comment by dvdvideo1234** [comment]
Well, using `Color(rgba)` is the way to go to create one and use it for whatever

**Pull request closed without merging**
