### PR TITLE
Make the gmod cursor great again

### PR DESCRIPTION
**Pull request by Velkon**
Before: 
After:  

2017 Cursor.

### CODE REVIEW

**Comment by AMD-NICK** [comment]
\\_ 😦 _/

>] cl_software_cursor 1
--- Missing Vgui material vgui/cursors/hourglass

anyway cursor is visible

**Comment by mcNuggets1** [comment]
It looks ugly. (Too big sized)

**Comment by SpencerSharkey** [comment]
no

**Comment by BlackCetha** [comment]
The "hitpoint" isn't on the tip aswell.
This will take some unneccessary time getting used to.

**Comment by mcNuggets1** [comment]
I got nightmares from steam big picture.
This reminds me of it.

**Comment by Linkfan123** [comment]
Did they just steal the cursor from CS:GO?

hOw cOuLd tHeY

Also I hate games which change the cursor. Just leave me with the default cursor. IDFC.

**Comment by Kefta** [comment]
You can disable it with a command

**Pull request closed without merging**
