### PR TITLE
TTT: more translatability improvements and fixes

### PR DESCRIPTION
**Pull request by r47orr**
- Implement actual translations for TTT start new game menu

- Implement actual translations for mute states notifications on chat, thus removing its hardcodes

- Remove hardcodes and refactor hl2 ents replacements for maps with no spawnscripts

- Suggest new effect and sound for discombulator and remove its pulling function related to non-players (only push stuff away)

- This is a complement for c833b5892875a7c7c0a1fdf112d1d34653a4669d by @svdm, trying to fix Facepunch/garrysmod-issues#3544 (one of the pendencies from it)

PS: I'd also recommend transfering all of the TTT lang files to Crowdin, to improve the translatability for the translator's community. I've tested it the english lang file, and it works. Not as straightforward as the rest of the translation, it will involve respecting the syntax and stuff like that, but it could work pretty well.

### CODE REVIEW

**Comment by robotboy655** [comment]
TTT translations should be kept separate from the base game. It should still work from the gamemode's content folder.

**Comment by r47orr** [comment]
> TTT translations should be kept separate from the base game. It should still work from the gamemode's content folder.

> I even discussed this yesterday with the author of this PR privately. Wouldn't they cause incompatibilities because Garry's Mod uses `.properties` files and TTT uses `.lua` files which contain different spacing?

I don't understand exactly why keep the translations in this repo. It is way better for revision and organisation to keep all content related to translation on Crowdin since it is a translation-based community, and I say and suggest that based on my experience as a translator. I've been a translator for Valve on Steam since STS (Steam Translation Server - that is, before they moved it to Crowdin) and they used to keep all of the localisation files for all of their games on it, and now moved them onto Crowdin, and it still is a great system and works pretty well. And since you already have "moderators" for the languages related to Gmod, it would also be good to have them contributing directly to TTT's translation as well, since not every translator knows how to use GitHub and that also makes it difficult for them to contribute and for you (managers) to approve and keep track of the translation progress, since it mixes the translation of it with development suggestions in this repo's PRs

**Comment by r47orr** [comment]
> I even discussed this yesterday with the author of this PR privately. Wouldn't they cause incompatibilities because Garry's Mod uses `.properties` files and TTT uses `.lua` files which contain different spacing?

Nope, that doesn't interfere. What is being used in the gamemode's txt file `terrortown.txt` is something implemented through the engine. That text file has nothing to do with the Lua API used in the gamemode's source code. Also, I've tested those changes, and that translation implementation for the start new game section does work normally, just like it works for Sandbox and any other gamemodes that could be in the game. They just need to have the strings in the `main_menu.properties` file

**Comment by Satton2** [comment]
Oh... I see my old issue got on the spotlight. That was unexpected.

Let me also add something from myself.

I was having quite much pain in the... fingers while localizing and finding different strings in the code or in-game while making a complete overhaul of the original TTT. GitHub isn't something localizators should deal with, that's for sure. I am also telling that from the perspective of me, who made an unofficial Russian localization for DarkRP and official localization of TTT2 both via GitHub. It's also quite hard to control all the changes when you literally don't have any straight notifications about it, so you can miss something that may result in getting kinda messed localization.

As an old STS translator and a Russian proofreader for Garry's Mod localization project on Crowdin, I must say that Crowdin is a good platform for any file format. However, when I got to the Garry's Mod localization project, I got almost a straight warning that states "_there are almost zero chances to get a new proofreader for any reason_". I got my "chance" to make localization actually better by some very good luck, and I still feel the Rubat's stare at me to tell me how he want to crush my skull and... well, I believe he still doesn't like my localization because he got some complaints about it, which wasn't explained what exactly they were about (got explanation from some of complainers through PM, so some of them are fixed).

Since GMod's Crowdin probably not going to get new proofreaders, the localization will have some problems like:
- constant inconsistency in terminology and the translation;
- never ending "localization war of votes" that at one point resulted in some unwanted results (_oh, I remember that day that due to the Crowdin vote system, Rust got many texts replaced with an abusive word that actually got into the game_)
- never changing approved strings (_YEAP, that is the current problem of some localizations because old proofreaders left and there are a bunch of translation that just stuck since they are approved!_)

Well, it's something that gets solved by giving a language at least one proofreader. And not gonna lie, GitHub is still worse, I still remember that damn "F*ck-o-stick" in the Russian localization of TTT being there **for years** and no one ever changed it before my localization overhaul.

I also want to remind that there is an old Issue (https://github.com/Facepunch/garrysmod-issues/issues/2580) that contains many strings that should be on Crowdin since they are related to the game itself but they are not. So...

Anyway, I would like to see TTT on Crowdin, or at least get missing strings on GitHub, but in the first case, this would be pointless if there would be no proofreaders, and in the second case, anyone will be able to ruin a localization since both, Facepunch developer and @svdm (btw, you should probably be here), can't actually check every language.

**Comment by r47orr** [comment]
> Anyway, I would like to see TTT on Crowdin, or at least get missing strings on GitHub, but in the first case, this would be pointless if there would be no proofreaders, while in the second case, anyone will be able to ruin a localization since both, Facepunch developer and @svdm (btw, you should probably be here), can't actually check every language, while users kinda can.

What I really wanted to understand is that discase they are showing towards the TTT gamemode. I don't quite understand, and, at least for me, looks like you guys at Facepunch kinda hate TTT. And for me, that doesn't make any sense, since the game is shipped with it, and, let's agree with the fact that TTT is probably one of the most important aspects of the whole game. We don't even need to do any research to get to the conclusion that probably most of the fame Garry's Mod has is because of TTT. 

And yes, I do think I understand that maybe you want to respect the author of the gamemode and leave the decisions to him, but many aspects and stuff related to TTT seem to be abandoned by Facepunch developers completely. Like, what is the big issue with implementing the gamemode's translation on Crowdin along with the main game strings? Why didn't you implement an important detail of the game (translation for TTT's start new game screen)? That is something fundamental in the game. 

Like it or not, the gamemode is shipped along the base game, thus making it a part of it, and also influencing the overall quality of the game. So TTT also deserves more attention, since you're still trying to maintain Garry's Mod...

So yeah, I don't know if I misinterpreted the whole thing, but at least for me, keeping a Gmod server and trying to send contributions, the gamemode and the base game maintainers seem to have a big conflict and a big denial towards each other.

**Comment by svdm** [comment]
Couple things here, I'll respond point by point starting with the PR:

> * Implement actual translations for TTT start new game menu
> 
>  * Implement actual translations for mute states notifications on chat, thus removing its hardcodes
> 

This part works for me if you can move it to a separate PR.

>  * Remove hardcodes and refactor hl2 ents replacements for maps with no spawnscripts
> 

I don't think this is necessary.

>  * Suggest new effect and sound for discombulator and remove its pulling function related to non-players (only push stuff away)
> 

Also don't think this is necessary, it's working as intended.


> Crowdin

I am not against doing the translations via Crowdin. The only reason TTT's translations are different/separate is because I implemented the system before Gmod had its current system.

> So yeah, I don't know if I misinterpreted the whole thing, but at least for me, keeping a Gmod server and trying to send contributions, the gamemode and the base game maintainers seem to have a big conflict and a big denial towards each other.

I don't have any conflict with Gmod/Facepunch. The simple fact is I'm not paid to work on TTT (never have been), and I don't personally play TTT or Gmod anymore. So anything I do for TTT is done in my free time, just because I would like people to be able to continue playing it.

Now I do have other things I like to do with my free time, so I'm not going to spend a ton on TTT. At the same time I don't really want other people to make major changes without my involvement, because I would like to make sure the game does not get ruined. All of this means that there will be no big changes to the core game. I think that's fine, TTT is over 10 years old and there are other gamemodes that build on it people can also play (e.g. [TTT2](https://github.com/TTT-2/TTT2) and others).

None of this really affects translations/Crowdin, as that does not involve the core game and I'm fine with any method of getting translations done.

**Comment by r47orr** [comment]
> Couple things here, I'll respond point by point starting with the PR:
> 
> > * Implement actual translations for TTT start new game menu
> > * Implement actual translations for mute states notifications on chat, thus removing its hardcodes
> 
> This part works for me if you can move it to a separate PR.
> 
> > * Suggest new effect and sound for discombulator and remove its pulling function related to non-players (only push stuff away)
> 
> Also don't think this is necessary, it's working as intended.
> None of this really affects translations/Crowdin, as that does not involve the core game and I'm fine with any method of getting translations done.

Thanks for the response. I will move the accepted parts to another PR. I just have two points here:

> 
> > * Remove hardcodes and refactor hl2 ents replacements for maps with no spawnscripts
> 
> I don't think this is necessary.
I'd say this part would be good to implement since the current system does not include all current TTT weapons and ents, and the suggested one would probably (besides including all of them and making it easier to increase) optimize how it runs.

And about the translation, it was weird that we suggested it and Rubat just answered "No. They are to be kept separate from the base game." and disappeared. But I and more translators hope we can see that change happening since to this day lots and lots of people still play TTT a lot every day and there are people wanting to collaborate with its translation, but it is too complicated to have it here on GitHub, since as you said it yourself, everything that happens to TTT needs your approval, and that complicates a lot the translation process as it is not necessary for you to be approving it all the time (not to cite the fact that translators need to have a GitHub account - which is not their "cup of tea" -, fork this repo and so on), since they already have revisors and "moderators" for translation on Crowdin. Maybe you could also talk to them about it?

That's all, thanks for answering :)

**Pull request closed without merging**
