### PR TITLE
Create info_player_commons.lua

### PR DESCRIPTION
**Pull request by BreakinBenny**
I got ahead of myself back there with my commits, didn't I. Let's just do it nice and easy…

If it's possible, can the trigger_joinhuman/zombie/spectatorteam brush entities be set up like "trigger_teleport" entities? The first two teleports you to a random human and zombie/whitey spawnpoint, whereas instead of becoming an Observer you get sent to either of the former three.

### CODE REVIEW

**Comment by robotboy655** [comment]
https://developer.valvesoftware.com/wiki/Info_player_common

Is it common or common**s**?

**Comment by Kefta** [comment]
Looks like commons:

**Comment by robotboy655** [comment]
Implementation of custom entities from mountable games is up to the modding community.

We only add spawnpoint entities so that the player is always spawned inside the level, not outside of it.

**Comment by robotboy655** [comment]
Come to think of it, do we even need this entity? We already have info_player_human and info_player_zombie from ZPS that worked well on all the maps in my testing.

**Comment by robotboy655** [comment]
Yeah the question do we need it, if you also need other entities to escape it.

**Comment by Kefta** [comment]
It at least gives a starting point for mods to expand upon. I think we should have a community discussion on how far GMod goes to support mountable games entity/weapon-wise.

**Comment by robotboy655** [comment]
If you are already installing a mod, the mod might as well add the entity.

GMod will not really support mountable game entities or weapons for obvious reasons of not having the source code for one. You don't mount games to play those games in GMod. GMod shouldn't a substitute to the mountable games.

**Comment by BreakinBenny** [comment]
Guess you could pretty much set up the info_player_commons and "Join team" brushes to be removed upon being spawned, then? Like a logic_auto that immediately removes itself upon triggering OnMapSpawn?

**Comment by robotboy655** [comment]
That's completely pointless, if an entity class doesn't exist, the entity is never spawned.

**Comment by BreakinBenny** [comment]
Then, is it better to just make the trigger_join%team% brushes act as func_teleports with the on StartTouch output that sends !activator (should be filtered to player) to a random human/zombie spawn? 

Maybe so, because you're pretty much being teleported to the spawnpoint (only without being either human or zombie in Garry's Mod). Some maps will require noclipping manually however, since the makers straight up expect players to just press F1, F2, or F3 o choose a team.

**Pull request merged**
