### PR TITLE
Fix `util.IsBinaryModuleInstalled` for menu binary modules

### PR DESCRIPTION
**Pull request by PrikolMen**

### CODE REVIEW

**Comment by PrikolMen** [comment]
I accidentally sent changes to the cl_keys.lua file, please ignore (skip) that file, I tried to undo them..

**Comment by FlorianLeChat** [comment]
Just recreate a clean pull request at this point (unless Rubat applies your changes manually)

**Comment by PrikolMen** [comment]
Yes, thats what I'm doing right now..

**Comment by PrikolMen** [comment]
https://github.com/Facepunch/garrysmod/pull/1927

**Pull request closed without merging**
