### PR TITLE
Remove bitch

### PR DESCRIPTION
**Pull request by colemclaren**
Not a nice word. There are better ways to say this comment.

### CODE REVIEW

**Comment by colemclaren** [comment]
I don't have any problems with any of the other words in the codebase. Of course, there are still bad words littered around where there should not be, but these are just the worst of them. It's important we promote a family-friendly environment for schools to be able to teach programming using Garry's Mod. This is one step closer to making it possible for teachers to be able to confidently teach their students how to begin programming.

**Comment by Down-s** [comment]
Grow up

**Comment by colemclaren** [comment]
> Grow up

The responsible thing to do is to just get rid of these unnecessarily inappropriate slurs in this codebase. It does nothing but turn minorities and women away from programming. This is not a joke. The world is changing. This garbage can be removed, it's not needed.

**Comment by swampservers** [comment]
I agree, this type of language is unprofessional and creates a very non-inclusive atmosphere in the Garry's Mod community which is toxic to women, homosexuals, and various other marginalized communities. I believe this codebase needs a thorough review to be brought more in line with modern inclusive language principles. https://developers.google.com/style/word-list?hl=en

**Comment by nodgear** [comment]
This commit removes the soul of facepunch.
the name of the company is facepunch
think about that.

**Comment by colemclaren** [comment]
> This commit removes the soul of facepunch. the name of the company is facepunch think about that.

Speed bump! This is a school zone. You need to slow down! Bitch is a sexist slur. Just because the company's name is Facepunch does not make it okay to degrade women.

**Comment by Kefta** [comment]
I have to somewhat agree that it does remove the soul or at least the character of the codebase. This is not a professional codebase constructed by a corporation over the course of a decade, it was one man's project with many community contributions afterwards. The comments that have bled into the codebase over time are a reflection of the frustrations and personality of the programmer that wrote them which is also clear by the approaches to solving an issue that are present. GMod may be a common introduction to programming for kids - it certainly was for me, but the comments here are using swears not to be offensive, political, or racy but rather in context of the code they describe. Removing hairy cocks, sure, it was just Garry fucking about as he does, but this one actually describing code below - in a brash way sure but that's a reflection of Garry. I still chuckle when I see a scornful comment in the Source leak codebase that contains a swear knowing they must've spent weeks to months on a singular issue, only to get some release by venting in a comment. Codebases like these which are not subject to polished, sterile review processes and strict contribution restrictions can breathe with life thru comments like these and I believe this, as well as the rest of the comments that are in reference to specific code, should stay.

**Comment by colemclaren** [comment]
> I have to somewhat agree that it does remove the soul or at least the character of the codebase.

The soul and character were lost when the repository was transferred from /garrynewman to /facepunch. Come back to Earth. This is a company, many of which take extremely serious. Garry's Mod is my career. This is not very progressive of you at all. As a rights activist, it's important we provide an environment for all types of people. This is not changing a lot, this is such a tiny change.

**Comment by Kefta** [comment]
Facepunch is still at its core Garry. This is not a highly hierarchical company. If that were the case, code standardisation, unit tests, and proper review procedures would have been put in place. Even if you were a rights activist like you claim, you are still removing "ASS" from the TTT repo: who's rights are you fighting for there?

**Comment by colemclaren** [comment]
> who's rights are you fighting for there?

Ass is not helpful for men doing no-nut, dead serious. I do not want to think of ass. I should not have to be reminded of ass when I program. I do not want to think of ass when I program. I'm trying to keep my energy to myself and when inappropriate words, especially ass, pop up out of nowhere all of a sudden I have blue balls for no reason.

**Comment by colemclaren** [comment]
I do not want these comments on my server and I refuse to edit base Garry's Mod files. This needs to change.

**Comment by Kefta** [comment]
I was only making these comments for good-faith contributors who may hold that this language is dangerous for future's sake but you clearly haven't been one from the beginning. This is a stunt for attention and your refusal to edit base files (ones that you will probably never touch/modify anyway since that's the whole point of going into the file, and if you do you can make local copies without the comments) gives it away. Make your new TTT community but stop flooding the repo with these obvious ploys for exposure.

**Comment by colemclaren** [comment]
I hope this gets no exposure at all. This should be merged and swept under the rug. Not a good look for the company. I feel personally attacked by your response.

**Comment by colemclaren** [comment]
> I was only making these comments for good-faith contributors who may hold that this language is dangerous for future's sake but you clearly haven't been one from the beginning. This is a stunt for attention and your refusal to edit base files (ones that you will probably never touch/modify anyway since that's the whole point of going into the file, and if you do you can make local copies without the comments) gives it away. Make your new TTT community but stop flooding the repo with these obvious ploys for exposure.

I think you misunderstood what I meant by "edit base Garry's Mod files". I did not mean this repository. I mean the files on any local game server since any changes made to them will be reverted when a game update is ran.

**Comment by WilliamVenner** [comment]
> It's important we promote a family-friendly environment for schools to be able to teach programming using Garry's Mod.

Nobody is doing this. Scratch and ROBLOX already won here. Schools are not going to install Steam on their computers, and sure as hell aren't going to install Garry's Mod (and not because of some naughty words in the codebase)

Only developers see this code. Beginners also never look at Facepunch/garrysmod code.

**Comment by colemclaren** [comment]
Listen man, these comments were made over a decade ago. Back then, this language was allowed. The world is different now, and people are a lot easier offended by words more than ever. I've been trying to make this change for over 5 years. I let it slip by me 5 years ago, but I'm putting my foot down here. The world is not what it used to be 10 years ago. Words hurt people. It takes all types of people to make a world.

**Comment by mcNuggets1** [comment]
Facepunch already lost all of my respect years ago with how greedy, customer unfriendly and arrogant they handled literally everything over the years.
Facepunch already lost the reputation it built up and sacrificed it for a better paycheck.

So keeping the soul of Facepunch alive is a bullshit argument.
There's no soul in this business whatsoever anymore.

Homphobic, racial slurs should be removed, I agree.
But words like "bitch"? Nobody is offended by that, because it is not about them.

**Comment by colemclaren** [comment]
I mean man, can we just make this more inclusive for women please? I want to be proud to show women my Garry's Mod code. I don't want to be scared they might read a word which offends them. The only pick up line I have at this point is my Garry's Mod code. There's nothing quite like my Garry's Mod code. The ladies would be all over me if I could just show them it.

**Comment by mcNuggets1** [comment]
I dont call women bitch only. I call that shit everyone.
Maybe instead of removing all slurs just let speech evolve.
I don't think removing words completely is even morally the right way.

**Comment by WilliamVenner** [comment]
> Listen man, these comments were made over a decade ago. Back then, this language was allowed. The world is different now, and people are a lot easier offended by words more than ever. I've been trying to make this change for over 5 years. I let it slip by me 5 years ago, but I'm putting my foot down here. The world is not what it used to be 10 years ago. Words hurt people. It takes all types of people to make a world.

The whole world is not California.

> Homophobic, racial slurs should be removed, I agree.
> But words like "bitch"? Nobody is offended by that, because it is not about them.

Agreed.

> **The only pick up line I have at this point is my Garry's Mod code. There's nothing quite like my Garry's Mod code. The ladies would be all over me if I could just show them it.**

Well, show's over folks.

**Comment by colemclaren** [comment]
I've made a post on Twitter. https://twitter.com/WallyWaylove/status/1554854686225842177

**Comment by mcNuggets1** [comment]
> 

You have to be kidding me.
You brought this to twitter?
Fucking hell. I'm outta here.
Have a good one, boys.

This person is out of their minds.

**Pull request closed without merging**
