### PR TITLE
info_player_commons and more

### PR DESCRIPTION
**Pull request by BreakinBenny**
Spawnpoint for players not currently participating in the battle in ZPS. Is it perhaps possible to choose a random teleport destination for the trigger_joinhumanteam and trigger_joinzombieteam entities? If a player collides with the trigger_joinspectatorteam brush entity, choose either of the two former ones.

Also included are some tweaks I thought could be of use.

### CODE REVIEW

**Comment by robotboy655** [comment]
Why does this PR modify some files unrelated to the PR?

**Comment by BreakinBenny** [comment]
@robotboy655 I made additional tweaks that I thought'd be needed, with emphasis on _I_. For instance, the localization tag for the Console Toggle.

**Comment by Kefta** [comment]
PRs should serve one purpose per request, not put a bunch of unrelated changes together. Also, I don't think the cubemap weapon should be in the spawnmenu since it's a developer tool.

**Comment by BreakinBenny** [comment]
@Kefta I guess you'll add the changes yourselves, then?

**Comment by Kefta** [comment]
No, separate your changes into different PRs and they can be reviewed individually.

**Pull request closed without merging**
