### PR TITLE
Add GetConVarCache

### PR DESCRIPTION
**Pull request by garryspins**
Pretty self explanatory on how this would be useful

### CODE REVIEW

**Comment by Kefta** [comment]
It's not self-explanatory, the cache is an implementation detail. Why do you need this?

**Comment by garryspins** [comment]
since theres no built-in way of getting a table of convars this seemed like the lightest way to get a semi-complete list of them without detouring

this is 100% useless if a method of getting every convar is added

**Comment by Kefta** [comment]
> since theres no built-in way of getting a table of convars this seemed like the lightest way to get a semi-complete list of them without detouring
> 
> this is 100% useless if a method of getting every convar is added

Not only does this not contain every convar (and constantly changes), I don't see a reason why you'd need such a list. What use is having all convars?

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/341

This is not the answer.

**Pull request closed without merging**
