### PR TITLE
GetConVarNumber deprecated

### PR DESCRIPTION
**Pull request by Kumo4031**
Updated to ConVar object.

### CODE REVIEW

**Comment by Kefta** [comment]
I know the original used GetConVarNumber, but you should use GetBool here, instead, as it's only checking if the convar is enabled.

**Comment by Kumo4031** [comment]
> I know the original used GetConVarNumber, but you should use GetBool here, instead, as it's only checking if the convar is enabled.

True, don't know why I didn't think of that. Fixed in https://github.com/Facepunch/garrysmod/pull/1616/commits/f8ff79a1930258bf7d87503497f6f71956d27cb5

**Comment by Kefta** [comment]
You still need the outer if-statement parentheses for codebase consistency. Should be ``if ( mp_falldamage:GetBool() ) then``

**Comment by Kumo4031** [comment]
> You still need the outer if-statement parentheses for codebase consistency. Should be `if ( mp_falldamage:GetBool() ) then`

Done.

**Comment by robotboy655** [comment]
This is not a performance problematic place to get rid of `GetConVarNumber`  and most of performance issues with `GetConVarNumber`  were resolved by caching the internal convar objects.

I am considering undeprecating `GetConVar*` functions and adding a note about performance.

Changes like this just uglify the code for no benefit.

**Comment by Kefta** [comment]
This still saves a hashtable lookup every time. I think they should stay deprecated.

**Comment by robotboy655** [comment]
Does it matter in this particular case though?

**Comment by Kefta** [comment]
Not particularly.

**Pull request merged**
