### PR TITLE
Add Tooltip accessors

### PR DESCRIPTION
**Pull request by Kefta**
Solves https://github.com/Facepunch/garrysmod-requests/issues/514

### CODE REVIEW

**Comment by zerfgog** [comment]
please don't introduce aliases

**Comment by Kefta** [comment]
I have to since the modifier has one. I'll deprecate both when this gets accepted.

**Comment by Bo98** [comment]
I understand why you added it but I honestly don't see the point of adding an alias if we are just going to tell everyone not to use it. That's my opinion anyway.

**Comment by Kefta** [comment]
If I can remove the SetToolTip aliases, I won't add these. However, I would rather remove them at the same time instead of having a discrepancy.

**Comment by Kefta** [comment]
@zerfgog @Bo98 Which one is deprecated -- Tooltip or ToolTip?

**Comment by Bo98** [comment]
http://wiki.garrysmod.com/page/Panel/SetToolTip

**Comment by Kefta** [comment]
@Bo98 Thanks!

**Comment by Kefta** [comment]
@robotboy655 Can this be merged?

**Pull request merged**
