### PR TITLE
Update weapon_alyxgun.txt

### PR DESCRIPTION
**Pull request by BreakinBenny**
Setting holdtype to pistol and giving it the SMG1's reload sound, just because. Might as well reference the E3 showcase when the pistol reused that.

### CODE REVIEW

**Comment by robotboy655** [comment]
Why changing the hold type in that file necessary?
Why changing the reload sound is necessary? Is the current sound script not working?

"Just because" is not a good reasoning for anything.

**Comment by BreakinBenny** [comment]
Currently, players holding the Alyxgun use the "unarmed" animation instead of aiming it like a handgun. Also no, I couldn't hear the reload sound upon reloading.

**Comment by Kefta** [comment]
It's because a lot of the Weapon_Alyx_Gun.* sounds don't have sound manifest defines or the pointed sound effects don't exist. This should just be fixed by mods that restore HL2 Beta behaviour.

**Comment by robotboy655** [comment]
Please also test your own changes next time. Changing "anim_prefix" doesn't affect player hold type in-game.

**Comment by BreakinBenny** [comment]
I suppose changes to weapon scripts are only in effect in Singleplayer Source games and mods, like SMOD then. I promise not to hold my breath.

**Pull request closed without merging**
