### PR TITLE
Add Unpack, SetUnpacked, and ToTable to Color

### PR DESCRIPTION
**Pull request by Kefta**
To go along with https://github.com/Facepunch/garrysmod-requests/issues/515

### CODE REVIEW

**Comment by meepdarknessmeep** [comment]
what the fuck

**Comment by Kefta** [comment]
It'd be faster for these to be implemented in C since in Lua, you'd have to call _Index three times and cross the C boundary.

**Comment by meepdarknessmeep** [comment]
color is lua

**Comment by Kefta** [comment]
Wrong page; read the issue instead

**Comment by Kefta** [comment]
Added additional relevant functions

**Pull request merged**
