### PR TITLE
Add option to make hands skin match player skin

### PR DESCRIPTION
**Pull request by thegrb93**
Not tested yet, but opening for review

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
>Not tested yet

**Comment by thegrb93** [comment]
Don't wanna waste the time testing if its just gonna get rejected anyway

**Comment by thegrb93** [comment]
It works. I also changed the if else into ternary

**Comment by thegrb93** [comment]
Now it works

**Comment by thegrb93** [comment]
Alternatively can use `self.Player:GetInfoNum( "cl_playerskin", 0 )` instead of pl:GetSkin() and revert the change to pl:SetupHands()

**Review by robotboy655 — APPROVED** [review]

**Pull request merged**
