### PR TITLE
Update menu.html

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by robotboy655** [comment]
Ok, what is the point of this? Especially a screenshot button in main menu which will just take a picture of the main menu?

**Comment by MoskalykA** [comment]
> Ok, what is the point of this? Especially a screenshot button in main menu which will just take a picture of the main menu?

The goal is to have different shortcuts. What if when we do a screeenshot we get a picture of where we are.

**Comment by GitSparTV** [comment]
But this will take a screenshot of the main menu as well...

**Comment by MoskalykA** [comment]
OKey thanks

**Comment by MoskalykA** [comment]
You don't have to.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/pull/1668

**Pull request closed without merging**
