### PR TITLE
Optimized player.GetBySteamID/player.GetBySteamID64

### PR DESCRIPTION
**Pull request by afxnatic**
instead of doing a full loop through player.GetAll, this creates a hashtable and updates it via OnEntityCreated/EntityRemoved

this is a draft PR as its best tested in a multiplayer environment and I can't really do that easily :(

### CODE REVIEW

**Comment by Malivil** [comment]
Does `util.SteamIDFrom64` give unique results for bots? I can't test right now, but if it returns "BOT" then this would break for bots.

**Comment by afxnatic** [comment]
fixed by rejecting the string returned by [Player:SteamID](https://wiki.facepunch.com/gmod/Player:SteamID) for bots, no need to do the same for [player.GetBySteamID64](https://wiki.facepunch.com/gmod/player.GetBySteamID64) because [Player:SteamID64](https://wiki.facepunch.com/gmod/Player:SteamID64) returns a different steamid for every bot

**Comment by afxnatic** [comment]
> Does `util.SteamIDFrom64` give unique results for bots? I can't test right now, but if it returns "BOT" then this would break for bots.

fixed by rejecting the string returned by [Player:SteamID](https://wiki.facepunch.com/gmod/Player:SteamID) for bots, no need to do the same for [player.GetBySteamID64](https://wiki.facepunch.com/gmod/player.GetBySteamID64) because [Player:SteamID64](https://wiki.facepunch.com/gmod/Player:SteamID64) returns a different steamid for every bot

**Comment by afxnatic** [comment]
superseded by #2161

**Pull request closed without merging**
