### PR TITLE
Fixed garry syntax

### PR DESCRIPTION
**Pull request by aStonedPenguin**
The moment many Garry's Mod developers have been waiting for has finally come. It is time to switch to vanilla lua syntax.

### CODE REVIEW

**Comment by mcd1992** [comment]
We're gonna beat you up so good when this breaks something.

**Comment by KingofBeast** [comment]
+23,725 −23,725
( ⚆ _ ⚆ )

**Comment by NotSoSuper** [comment]
have fun robotboy

**Comment by Velkon** [comment]
You hating on whitespace just cause it's white?

**Comment by Tenrys** [comment]
implying this will be accepted 💯 
you have shit like this in the code
`Vector( 1, 2, 3)`
why remove the space next to ) but not (

**Comment by Kefta** [comment]
I wouldn't remove the whitespace between parenthesis. While I personally don't use it anymore, it's consistent with the Source SDK syntax.

**Comment by aStonedPenguin** [comment]
@Tenrys It's still 50% better then what it was before.

**Comment by Tenrys** [comment]
not saying it isn't

**Comment by sirsavary** [comment]
I super strongly agree with this PR

While Garry Syntax is supported, using it out of the box is confusing, breaks existing editors and has caused more problems than it's worth.

**Comment by robotboy655** [comment]
no

**Comment by meepdarknessmeep** [comment]
maybe?

**Pull request closed without merging**
