### PR TITLE
Remove CanProperty from the base gamemode

### PR DESCRIPTION
**Pull request by CaptainPRICE**
I don't think it belongs there. Why is it there anyways?

### CODE REVIEW

**Comment by CaptainPRICE** [comment]
[It is Sandbox thing](https://wiki.garrysmod.com/page/SANDBOX/CanProperty).

**Comment by Kefta** [comment]
This should be moved to Sandbox's shared.lua.

**Comment by CaptainPRICE** [comment]
@Kefta 
> This should be moved to Sandbox's shared.lua.

huh wut?
But, it is already present there:
https://github.com/Facepunch/garrysmod/blob/b03cc1ed585eeb037e9f7723fc29ef4f570e1782/garrysmod/gamemodes/sandbox/gamemode/shared.lua#L201-L252

**Comment by Kefta** [comment]
Huh, must have missed that.

**Comment by robotboy655** [comment]
The properties system exists outside of Sandbox (In the `properties` module, and all built-in properties are loaded regardless of which gamemode is running, as well as any addon properties), so it only makes sense for clearly defined behavior for non Sandbox gamemodes to exist in the Base gamemode as well. 

It is kinda made even worse by the fact that `CanProperty` is called manually from each property and they test for "is allowed" in different ways.

**Pull request closed without merging**
