### PR TITLE
Update skill.cfg

### PR DESCRIPTION
**Pull request by NathanX-S**
these cause errors in the console (presumably not implemented)

### CODE REVIEW

**Comment by viral32111** [comment]
Wasn't this fixed in an update not too long ago?

**Comment by NathanX-S** [comment]
Maybe so, but in the current build of the game I still get these errors on my dedicated.

**Comment by robotboy655** [comment]
Maybe update your server then.

image

**Comment by GitSparTV** [comment]
imagine not updating the server

**Pull request closed without merging**
