### PR TITLE
Add table.FindMemberByKey( Table, key, val )

### PR DESCRIPTION
**Pull request by Tripperful**
Use case:

```Lua
local guys = {

	{
		age = 10,
		name = "John"
	},
	{
		age = 20,
		name = "Peter"
	},
	{
		age = 30,
		name = "Mike"
	},
}

print( table.FindMemberByKey( guys, "name", "Peter" ) )
```
Result:
```2       table: 0x2364fd78```

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Maybe nitpicking on mnemonics, but "GetMemberByColumn" might be better than "GetByMemberValue", because in Lua everything is a "value". Translates to "Retrieve the desired /member/ where its colum /name/ is /Peter/"

**Comment by robotboy655** [comment]
I kinda find this function to be bad, BECAUSE what if there's 2 entries with the same "Name" or "Age" field? Which one should be returned then?

**Comment by sannysc** [comment]
The first one it finds should be returned. This is already common behavior in the ```table``` library.

http://wiki.garrysmod.com/page/table/KeyFromValue
http://wiki.garrysmod.com/page/table/RemoveByValue

**Comment by Tripperful** [comment]
Changes some things. Thanks for the feedback.

> **robotboy655**: ... if there's 2 entries with the same "Name" or "Age" field? Which one should be returned then?

Maybe it would then make sense to better rename it to table.FindMembersByColumn and make it return a table of all found keys? It would act like a "database query", returning a "res" table, which can be nil or a table containing one or more elements

**Comment by sannysc** [comment]
Now this is even more confusing than before...There are no "columns" in tables. There are keys and there are values.

**Comment by Tripperful** [comment]
Changed some things once again

**Comment by Tripperful** [comment]
Hah, it's still rather confusing, the first thing I think of when I see such function name is "Oh, it probably just does ```return Table[key]```, what's the point..?". 

If someone has a good name for it - go ahead. Otherwise, if it will stay confusing, I will just close the PR. The community doesn't seem to like this proposal anyways.

**Pull request closed without merging**
