### PR TITLE
Add HL1 and Garry's Mod language strings

### PR DESCRIPTION
**Pull request by Kefta**
Moved all Garry's Mod entity print names over to the language file and added new HL1 weapon strings. Also cleaned up and sorted the language files.

### CODE REVIEW

**Comment by mcNuggets1** [comment]
Conflicting pullrequest.

**Comment by Kefta** [comment]
Fixed - conflict was from adding HL1 weapon translations which was already done in this pull request... @robotboy655

**Comment by robotboy655** [comment]
The ```Cubemap``` capitalization changes seem unnecessary.

If you are going for consistency, other existing translations (hl2 weps) are already inconsistent.

**Comment by Kefta** [comment]
Fair enough, changed it back.

**Comment by robotboy655** [comment]
```SATHEL CHARGE```

Also I do not agree with some of your HL1 weapon renames, I made them specifically different from the HL2 variants. (```RPG```, ```.357 MAGNUM```)

You also have 2 translations for ```"func_tankrocket"```, ```Physics Explosion``` to ```Explosion``` and ```Sitting Scientist``` changes also seem unnecessary.

**Comment by Kefta** [comment]
``SATHEL CHARGE`` -> ``SATCHEL CHARGE``
``RPG`` -> ``RPG LAUNCHER``
``.357 MAGNUM`` -> ``.357 HANDGUN``

I left the other weapons changed (``GLOCK``, ``MP5``, ``SPAS-12``) since those are the names listed on the Half-Life wiki and are cleaner than ``9MM XX`` imo. Removed the duplicate and reverted the renames.

**Pull request merged**
