### PR TITLE
[TTT] Distinguish Brazilian Portuguese and European Portuguese

### PR DESCRIPTION
**Pull request by Tiagoquix**
There are two mainly types of the Portuguese language. There is the Brazilian Portuguese spoken in Brazil, and European Portuguese spoken in Portugal.
Since this file is heavily translated into Brazilian Portuguese, I think it should have a separation between the two types, so if any European Portuguese person wants to create a new translation, he/she will be free to create it.

### CODE REVIEW

**Comment by Kefta** [comment]
You should keep the file in the lang folder.

**Comment by Tiagoquix** [comment]
> You should keep the file in the lang folder.

@Kefta Thanks for the warning! I committed a mistake and I didn't perceived.

**Comment by Donato555** [comment]
> There are two mainly types of the Portuguese language. There is the Brazilian Portuguese spoken in Brazil, and European Portuguese spoken in Portugal.
> Since this file is heavily translated into Brazilian Portuguese, I think it should have a separation between the two types, so if any European Portuguese person wants to create a new translation, he/she will be free to create it.

I heavily disagree with this change. First of all, written european and brazilian portuguese are a unified language, they are the same thing with different local manerisms (same as british english and american english). The major diferences between both appear only when they are spoken... since ttt only uses the written form i see absolutely no point in doing this. Not to mention that why was this done if the so called 'european' portuguese was not even added?

Furthermore all this did is basically break all the addons in brazilian servers that used portuguese translation, which we are now having to fix manually and reupload to workshop...

**Comment by Kefta** [comment]
Written European and Brazilian Portuguese are not "unified." Some spelling and construction of phrases are different, especially when it comes to using nouns directly as verbs. I will personally see to that European Portuguese is added.

**Comment by robotboy655** [comment]
> Furthermore all this did is basically break all the addons in brazilian servers that used portuguese translation, which we are now having to fix manually and reupload to workshop...

In what way? The language is still there.

**Comment by Donato555** [comment]
> Written European and Brazilian Portuguese are not "unified." Some spelling and construction of phrases are different, especially when it comes to using nouns directly as verbs. I will personally see to that European Portuguese is added.

Sorry, but are you even a portuguese speaker? Portuguese gramatic has been unified across it's spoken nations since 2009 with the gramatic reform (which was basically done so all portuguese speakers can mutually understand each other). The diferences between both languages in written terms are very minimal and mostly differ with local manerisms, how you form some specific phrases and some noums. A lad from portugal can read a text from brazil as if it was his own and vice versa, so i do not really understand why this was changed at all.

**Comment by Donato555** [comment]
> > Furthermore all this did is basically break all the addons in brazilian servers that used portuguese translation, which we are now having to fix manually and reupload to workshop...
> 
> In what way? The language is still there.

By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.

**Comment by Donato555** [comment]
If you want to add another language simply create a new file with it... there is 0 reason to change what was already there (specially since there isnt even the european 'variant' present, and i doubt very much that there will be)

**Comment by Tiagoquix** [comment]
> > > Furthermore all this did is basically break all the addons in brazilian servers that used portuguese translation, which we are now having to fix manually and reupload to workshop...
> > 
> > 
> > In what way? The language is still there.
> 
> By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.

As far as I know, the languages files are only used server-side (that is, the language files are loaded on the server-side instead of the client-side). You can just rename the `brazilian_portuguese.lua` to `portuguese.lua` and keep the cvar `ttt_lang_serverdefault` set to the value `Português`. Doing this, the addons will probably work normally again.

**Comment by Donato555** [comment]
> > > > Furthermore all this did is basically break all the addons in brazilian servers that used portuguese translation, which we are now having to fix manually and reupload to workshop...
> > > 
> > > 
> > > In what way? The language is still there.
> > 
> > 
> > By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.
> 
> As far as I know, the languages files are only used server-side (that is, the language files are loaded on the server-side instead of the client-side). You can just rename the `brazilian_portuguese.lua` to `portuguese.lua` and keep the cvar `ttt_lang_serverdefault` set to the value `Português`. Doing this, the addons will probably work normally again.

Yes... it is done server side, so the shared.lua of all translated terror and detective guns got errors and stopped working. Yes we already fixed that, i'm just annoyed that we had to fix them at all ... i mean the 'update' didnt even add 'european portuguese' into the game, so why tha hack was this made at all?

**Comment by Tiagoquix** [comment]
> > > > > Furthermore all this did is basically break all the addons in brazilian servers that used portuguese translation, which we are now having to fix manually and reupload to workshop...
> > > > 
> > > > 
> > > > In what way? The language is still there.
> > > 
> > > 
> > > By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.
> > 
> > 
> > As far as I know, the languages files are only used server-side (that is, the language files are loaded on the server-side instead of the client-side). You can just rename the `brazilian_portuguese.lua` to `portuguese.lua` and keep the cvar `ttt_lang_serverdefault` set to the value `Português`. Doing this, the addons will probably work normally again.
> 
> Yes... it is done server side, so the shared.lua of all translated terror and detective guns got errors and stopped working. Yes we already fixed that, i'm just annoyed that we had to fix them at all ... i mean the 'update' didnt even add 'european portuguese' into the game, so why tha hack was this made at all?

Well, I suggested the change and it was approved.
I just separated the two types of Portuguese because if someone wants to translate TTT to European Portuguese, they won't need to worry about the only portuguese translation and how they would separate it.

**Comment by svdm** [comment]
> 
> By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.

This is a good point I hadn't considered when I merged the change, sorry about that.

Do you have an example of an addon that had to update because this change made it error? When `LANG.AddToLanguage` is used it should only warn rather than break, so I suspect there is a TTT bug to fix there.

**Comment by Donato555** [comment]
> > By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.
> 
> This is a good point I hadn't considered when I merged the change, sorry about that.
> 
> Do you have an example of an addon that had to update because this change made it error? When `LANG.AddToLanguage` is used it should only warn rather than break, so I suspect there is a TTT bug to fix there.

It is ok, i understand things like this happen a lot in dev and the error was an easy fix. I just ask for a little caution when changing an existing file, and avoid doing it when there is no real need.

Also i sure can show the problem. I will take the Freeze Gun, a special equipment, as an example. In order to allow the description and the wep name to be translated, but not get rid of the english version (because some people use it) the first lines of the shared.lua are as follows: 

`if CLIENT then
	LANG.AddToLanguage("english", "freezegun_name", "Freeze Gun")
	LANG.AddToLanguage("Português", "freezegun_name", "Arma de Gelo") -- line 127
	
	LANG.AddToLanguage("english", "freezegun_desc", "Freezes the target for " .. freezeDuration:GetInt() .. " seconds.\nThe target can't move, look around,\nshoot or do anything else.\n\n" .. defaultClipSize:GetInt() .. " shots")
	LANG.AddToLanguage("Português", "freezegun_desc", "Congela o alvo por " .. freezeDuration:GetInt() .. " segundos.\nEle não pode se mover, olhar para os lados,\natirar ou fazer qualquer outra coisa.\n\n" .. defaultClipSize:GetInt() .. " tiros")
	
	SWEP.PrintName          = "freezegun_name"
	SWEP.EquipMenuData = {
      type = "item_weapon",
      desc = "freezegun_desc"
end
   };`

With the change, the Lang "Português" could no longer be found, and everyone got the following error: 

`Failed to add 'freezegun_name' to language 'português': language does not exist.
[ttt-freezegun] gamemodes/terrortown/gamemode/cl_lang.lua:54: attempt to index a nil value
  1. AddToLanguage - gamemodes/terrortown/gamemode/cl_lang.lua:54
   2. unknown - addons/ttt-freezegun/gamemodes/terrortown/entities/weapons/weapon_ttt_freezegun.lua:127
`

Since the translation to all available languages is done when the gun loads, even players using the english version got the error. As a result the weapon became unavailable at the equipment menu. The same thing happened to all custom weapons that had translations available.

This same weapon that was used as an example has chat messages when used,and said messages are also translated. However such is not done with the LANG.AddToLanguage so there were no code errors (a part from the portuguese translation becaming unavailable).

**Comment by Donato555** [comment]
> > By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.
> 
> This is a good point I hadn't considered when I merged the change, sorry about that.
> 
> Do you have an example of an addon that had to update because this change made it error? When `LANG.AddToLanguage` is used it should only warn rather than break, so I suspect there is a TTT bug to fix there.

It is ok, i understand things like this happen a lot in dev and the error was an easy fix. I just ask for a little caution when changing an existing file, and avoid doing it when there is no real need.

Also i show the problem. I will take the Freeze Gun, a special equipment, as an example. In order to allow the description and the wep name to be translated, but not get rid of the english version (because some people use it) the first lines of the shared.lua are as follows: 

`if CLIENT then
	LANG.AddToLanguage("english", "freezegun_name", "Freeze Gun")
	LANG.AddToLanguage("Português", "freezegun_name", "Arma de Gelo") -- line 127
	
	LANG.AddToLanguage("english", "freezegun_desc", "Freezes the target for " .. freezeDuration:GetInt() .. " seconds.\nThe target can't move, look around,\nshoot or do anything else.\n\n" .. defaultClipSize:GetInt() .. " shots")
	LANG.AddToLanguage("Português", "freezegun_desc", "Congela o alvo por " .. freezeDuration:GetInt() .. " segundos.\nEle não pode se mover, olhar para os lados,\natirar ou fazer qualquer outra coisa.\n\n" .. defaultClipSize:GetInt() .. " tiros")
	
	SWEP.PrintName          = "freezegun_name"
	SWEP.EquipMenuData = {
      type = "item_weapon",
      desc = "freezegun_desc"
end
   };
`

With the change, the Lang "Português" could no longer be found and everyone got the following error: 

`Failed to add 'freezegun_name' to language 'português': language does not exist.
[ttt-freezegun] gamemodes/terrortown/gamemode/cl_lang.lua:54: attempt to index a nil value
  1. AddToLanguage - gamemodes/terrortown/gamemode/cl_lang.lua:54
   2. unknown - addons/ttt-freezegun/gamemodes/terrortown/entities/weapons/weapon_ttt_freezegun.lua:127
`

Since the translation to all available languages is done when the gun loads, even players using the english version got the error. As a result the weapon became unavailable at the equipment menu. The same thing happened to all custom weapons that had translations available.

This same weapon that was used as an example has chat messages when used,and said messages are also translated. However such is not done with the LANG.AddToLanguage so there were no code errors (a part from the portuguese translation becaming unavailable).

**Comment by Donato555** [comment]
> > By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.
> 
> This is a good point I hadn't considered when I merged the change, sorry about that.
> 
> Do you have an example of an addon that had to update because this change made it error? When `LANG.AddToLanguage` is used it should only warn rather than break, so I suspect there is a TTT bug to fix there.

It is ok, i understand things like this happen a lot in dev and the error was an easy fix. I just ask for a little caution when changing an existing file, and avoid doing it when there is no real need.

Also i sure can show the problem. I will take the Freeze Gun, a special equipment, as an example. In order to allow the description and the wep name to be translated, but not get rid of the english version (because some people use it) the first lines of the shared.lua are as follows: 
 ```lua
if CLIENT then
	LANG.AddToLanguage("english", "freezegun_name", "Freeze Gun")
	LANG.AddToLanguage("Português", "freezegun_name", "Arma de Gelo") -- line 127
	
	LANG.AddToLanguage("english", "freezegun_desc", "Freezes the target for " .. freezeDuration:GetInt() .. " seconds.\nThe target can't move, look around,\nshoot or do anything else.\n\n" .. defaultClipSize:GetInt() .. " shots")
	LANG.AddToLanguage("Português", "freezegun_desc", "Congela o alvo por " .. freezeDuration:GetInt() .. " segundos.\nEle não pode se mover, olhar para os lados,\natirar ou fazer qualquer outra coisa.\n\n" .. defaultClipSize:GetInt() .. " tiros")
	
	SWEP.PrintName          = "freezegun_name"
	SWEP.EquipMenuData = {
      type = "item_weapon",
      desc = "freezegun_desc"
end
   };
```lua
With the change, the Lang "Português" could no longer be found, and everyone got the following error: 
```
Failed to add 'freezegun_name' to language 'português': language does not exist.
[ttt-freezegun] gamemodes/terrortown/gamemode/cl_lang.lua:54: attempt to index a nil value
  1. AddToLanguage - gamemodes/terrortown/gamemode/cl_lang.lua:54
   2. unknown - addons/ttt-freezegun/gamemodes/terrortown/entities/weapons/weapon_ttt_freezegun.lua:127
```

Since the translation to all available languages is done when the gun loads, even players using the english version got the error. As a result the weapon became unavailable at the equipment menu. The same thing happened to all custom weapons that had translations available.

This same weapon that was used as an example has chat messages when used,and said messages are also translated. However such is not done with the LANG.AddToLanguage so there were no code errors (a part from the portuguese translation becaming unavailable).

**Comment by Donato555** [comment]
It is ok, i understand things like this happen a lot in dev and the error was an easy fix. I just ask for a little caution when changing an existing file, and avoid doing it when there is no real need.

Also i sure can show you the problem. I will take the Freeze Gun, a special equipment, as an example. In order to allow the description and the wep name to be translated, but not get rid of the english version (because some people use it) the first lines of the shared.lua are as follows: 

 ```lua
if CLIENT then
	LANG.AddToLanguage("english", "freezegun_name", "Freeze Gun")
	LANG.AddToLanguage("Português", "freezegun_name", "Arma de Gelo") -- line 127
	
	LANG.AddToLanguage("english", "freezegun_desc", "Freezes the target for " .. freezeDuration:GetInt() .. " seconds.\nThe target can't move, look around,\nshoot or do anything else.\n\n" .. defaultClipSize:GetInt() .. " shots")
	LANG.AddToLanguage("Português", "freezegun_desc", "Congela o alvo por " .. freezeDuration:GetInt() .. " segundos.\nEle não pode se mover, olhar para os lados,\natirar ou fazer qualquer outra coisa.\n\n" .. defaultClipSize:GetInt() .. " tiros")
	
	SWEP.PrintName          = "freezegun_name"
	SWEP.EquipMenuData = {
      type = "item_weapon",
      desc = "freezegun_desc"
end
   };
```
With the change, the Lang "português" could no longer be found, and everyone got the following error:
 
```lua
Failed to add 'freezegun_name' to language 'português': language does not exist.
[ttt-freezegun] gamemodes/terrortown/gamemode/cl_lang.lua:54: attempt to index a nil value
  1. AddToLanguage - gamemodes/terrortown/gamemode/cl_lang.lua:54
   2. unknown - addons/ttt-freezegun/gamemodes/terrortown/entities/weapons/weapon_ttt_freezegun.lua:127
```

Since the translation to all available languages is done when the gun loads, even players using the english version got the error. As a result the weapon became unavailable at the equipment menu. The same thing happened to all custom weapons that had translations.

This same weapon that was used as an example also has chat messages when used, and said messages are also translated. However such is not done with the LANG.AddToLanguage so there were no code errors (a part from the portuguese translation becaming unavailable because again a 'português' lang no longer existed).

**Comment by Donato555** [comment]
> > By changing the name of the language, addons could no longer add a translation to "Português" because they could no longer find it under that name, thus launching a code error and not working anymore.
> 
> This is a good point I hadn't considered when I merged the change, sorry about that.
> 
> Do you have an example of an addon that had to update because this change made it error? When `LANG.AddToLanguage` is used it should only warn rather than break, so I suspect there is a TTT bug to fix there.

It is ok, i understand things like this happen a lot in dev and the error was an easy fix. I just ask for a little caution when changing an existing file, and avoid doing it when there is no real need.

Also, i sure can show you the problem. I will take the Freeze Gun, a special equipment, as an example. In order to allow the description and the wep name to be translated, but not get rid of the english version (because some people use it) the first lines of the shared.lua are as follows: 
 ```lua
if CLIENT then
	LANG.AddToLanguage("english", "freezegun_name", "Freeze Gun")
	LANG.AddToLanguage("Português", "freezegun_name", "Arma de Gelo") -- line 127
	
	LANG.AddToLanguage("english", "freezegun_desc", "Freezes the target for " .. freezeDuration:GetInt() .. " seconds.\nThe target can't move, look around,\nshoot or do anything else.\n\n" .. defaultClipSize:GetInt() .. " shots")
	LANG.AddToLanguage("Português", "freezegun_desc", "Congela o alvo por " .. freezeDuration:GetInt() .. " segundos.\nEle não pode se mover, olhar para os lados,\natirar ou fazer qualquer outra coisa.\n\n" .. defaultClipSize:GetInt() .. " tiros")
	
	SWEP.PrintName          = "freezegun_name"
	SWEP.EquipMenuData = {
      type = "item_weapon",
      desc = "freezegun_desc"
};
end
```
With the change, the Lang "Português" could no longer be found, and everyone got the following error: 
```lua
Failed to add 'freezegun_name' to language 'português': language does not exist.
[ttt-freezegun] gamemodes/terrortown/gamemode/cl_lang.lua:54: attempt to index a nil value
  1. AddToLanguage - gamemodes/terrortown/gamemode/cl_lang.lua:54
   2. unknown - addons/ttt-freezegun/gamemodes/terrortown/entities/weapons/weapon_ttt_freezegun.lua:127
```

Since the translation to all available languages is done when the gun loads, even players using the english version got the error. As a result the weapon became unavailable at the equipment menu. The same thing happened to all custom weapons that had translations available.

This same weapon that was used as an example has chat messages when used,and said messages are also translated. However such is not done with the LANG.AddToLanguage so there were no code errors (a part from the portuguese translation becaming unavailable).

**Comment by svdm** [comment]
Right, I suspected that was the issue. AddToLanguage is only supposed to print the "Failed to add..." message and continue, rather than blowing things up entirely. That's fixed in e6baa1b99f20613efe0f59c5e357f741ba002a4c. This way you would have been able to at least use the weapon without translations, although it's still preferable not to rename languages going forward.

**Pull request merged**
