### PR TITLE
net: OnNetMessageReceived

### PR DESCRIPTION
**Pull request by ItsEris**
this is cool and possibly helpful to some, more or less just want it for my particular usecase

### CODE REVIEW

**Comment by thegrb93** [comment]
hook.Call bruh

**Comment by Kefta** [comment]
bruh moment

**Comment by Kefta** [comment]
I think this hook is harmful without the ability to rewind the net buffer - calling net.Read* will offset reading for the receiver.

**Comment by Donkie** [comment]
Maybe the hook should be called after the receiver function so the hook is more of a notice than a place to read stuff?

**Comment by thegrb93** [comment]
It's just plain bad. Have whatever addon you're trying to hook into call a hook. Don't add a hack that hooks into every net message.

**Pull request closed without merging**
