### PR TITLE
alt to walk in default config

### PR DESCRIPTION
**Pull request by Python1320**
Considering walking is used in many gamemodes this should be the default option.

### CODE REVIEW

**Comment by Noiwex** [comment]
Agreed, it's used a lot, like in RP and sit anywhere addon.

**Comment by willox** [comment]
how long has this not been default 😕

**Comment by Noiwex** [comment]
Default keybinds are somewhat broken, as I remember. Like, some keys can be bound to TF2 commands, or ENTER can be bound to +attack. It's a mess.

**Comment by Noiwex** [comment]
Some players even have F1/F2/F3/F4 stuff unbound from start.

**Comment by mcNuggets1** [comment]
I wondered previously why my mouse 3/4 was not bound to "last weapon" action.
it was all the time, but after I reinstalled the game, it was not anymore.

**Comment by dvdvideo1234** [comment]
Do you guys know when this is gonna be merged as it affects the ALT button of my Track assembly tool ?

**Comment by robotboy655** [comment]
image

**Comment by neico** [comment]
I guess it's worth mentioning that this won't retroactively change the bindings on the already existing configs, so if it causes issues with your stuff you might need to implement a workaround until everyone adjusted their config (which very much might never happen)

Tampering with individual person's configs isn't allowed or recommended for various reasons.

**Comment by dvdvideo1234** [comment]
@robotboy655 Hello, no I mean in the actual game not the github repo ;)

**Comment by Kefta** [comment]
It was already released in the last update.

**Comment by Kefta** [comment]
https://steamcommunity.com/games/garrysmod/announcements/detail/1667947676645780414

**Pull request merged**
