### PR TITLE
Update dalphabar.lua

### PR DESCRIPTION
**Pull request by MoskalykA**
Switch from Color(...) to color_white (Micro cache optimization)

### CODE REVIEW

**Comment by GitSparTV** [comment]
Please always provide description for your PRs

**Comment by FoksVHox** [comment]
This PR are point less, yes it'll save a very minor percentage of resources, but it'll be so minimal that you don't feel it or will see a difference.

**Comment by nodgear** [comment]
I would approve this PR just for the sake of consistency across files.
It's a good practice recommended by the wiki itself, so that's how the code in the game should be, but i don't see the reason why he's doing it in separated requests. Gather all code with inconsistency and push all at once...

**Comment by MoskalykA** [comment]
> I would approve this PR just for the sake of consistency across files.
> It's a good practice recommended by the wiki itself, so that's how the code in the game should be, but i don't see the reason why he's doing it in separated requests. Gather all code with inconsistency and push all at once...

Unfortunately, I don't know how to make a request and put all my suggestions into one.

**Comment by viral32111** [comment]
Just commit everything to the same fork then make a PR for that fork. If you're doing this directly from the GitHub website, you can make a single fork of the repo, make all changes there, then come back to this repo and make the PR. I think by default GitHub automatically creates a "patch" PR if you edit a file in a repository you don't own.

**Comment by Kefta** [comment]
Getting rid of constant Vector, Angle, Matrix, Color, etc. allocs in the GMod base code is the goal. This PR is fine.

**Pull request merged**
