### PR TITLE
Simplified tobool

### PR DESCRIPTION
**Pull request by mastopgunaf**

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
bruh

**Comment by mastopgunaf** [comment]
> bruh
> 

If I omit the "not not", it will return nil if it's given a nil instead of false, so not not has to be there. No bruh.

**Comment by Kefta** [comment]
Use @neico's solution, it's the easiest to read.

**Comment by mastopgunaf** [comment]
> Use @neico's second solution, it's the easiest to read.

Imagine using C operators in GMod in 2020... Why would you?

**Comment by ExtReMLapin** [comment]
Hello,
As I feel like we will not agree on what to do, I decided to compile it to Lua 5.1 bytecode.
You can now load the bytecode using this interpreter : 

https://raw.githubusercontent.com/Rerumu/Rerubi/master/Source.lua
[bytecode.out](https://github.com/Facepunch/garrysmod/files/5119679/bytecode.txt)

**Comment by Kefta** [comment]
@mastopgunaf Because it's the accepted style of the codebase at the moment. We can evaluate changing it all in the future, but for now, stick with the common style or this won't be accepted.

**Comment by mastopgunaf** [comment]
> @mastopgunaf Because it's the accepted style of the codebase at the moment. We can evaluate changing it all in the future, but for now, stick with the common style or this won't be accepted.

I changed it to those terrible operators, should be ok now.

**Comment by Kefta** [comment]
The double ``!`` is still unreadable, but whatever I guess.

**Comment by robotboy655** [comment]
What is this meant to achieve?

**Pull request closed without merging**
