### PR TITLE
PData using SteamID64 to prevent collisions

### PR DESCRIPTION
**Pull request by ghost**
Changed PData from UniqueID to SteamID64 to prevent any collision between players.

### CODE REVIEW

**Comment by sanny-io** [comment]
This is a breaking change.

**Comment by FlorianLeChat** [comment]
See #1639 for more information.

**Comment by Kapsulon** [comment]
Then why not either, make so the function uses SteamID64() automatically if the value does not exist for the UniqueID(), or create a separate function like GetPData64() and SetPData64() as a new way to store data quickly ?

**Comment by Kefta** [comment]
The functions should be separate, not use an argument to change this altering behaviour.

**Comment by Kapsulon** [comment]
Here i just created 3 separate functions with alternative naming so old code doesn't get screwed

**Comment by robotboy655** [comment]
I have decided to go in a different direction in resolving the issue of using `UniqueID` for PData that is more transparent to existing addons, see here:
https://github.com/Facepunch/garrysmod/commit/8fc4e6d064ba249343dd22d24ab9e753c986d6d0

**Pull request closed without merging**
