### PR TITLE
Don't draw overlay with invisible ents

### PR DESCRIPTION
**Pull request by thegrb93**
Keeps overlay from drawing on invisible sents

### CODE REVIEW

**Comment by thegrb93** [comment]
Fuck editing on github. fucking shit

**Comment by thegrb93** [comment]
Can't do crlf on github so will fix later

**Comment by thegrb93** [comment]
@robotboy655 @Kefta

**Comment by robotboy655** [comment]
Ehhh I am not too sure about the alpha = 0 case.

**Comment by thegrb93** [comment]
@robotboy655 i'm fine with just the nodraw. Hows this?

**Pull request merged**
