### PR TITLE
Add ent:AddHealth()

### PR DESCRIPTION
**Pull request by Down-s**
This would be a big time saver

### CODE REVIEW

**Comment by WilliamVenner** [comment]
The clamping functionality of this makes it useful. +1

**Comment by FlorianLeChat** [comment]
When it will be added, maybe do the same thing with `Player:AddArmor()`.

**Comment by Down-s** [comment]
> When it will be added, maybe do the same thing with `Player:AddArmor()`.

Thanks, created a PR for it

**Comment by TomDotBat** [comment]
Probably should've just updated this one and changed the title instead of making another.

**Comment by Kefta** [comment]
As discussed in the Discord, there's the whole problem of a player having over the max health and this function reverting it to the max. I believe this should be implemented selectively in people's code to deal with this behaviour in their own way.

**Comment by Down-s** [comment]
> As discussed in the Discord, there's the whole problem of a player having over the max health and this function reverting it to the max. I believe this should be implemented selectively in people's code to deal with this behaviour in their own way.

I can add a check if the player's health is above max health, then add to that without clamping

**Comment by Kefta** [comment]
The behaviour of only adding if the health is already above the max health when the max health can change seems very specific and addon-implementable.

**Pull request closed without merging**
