### PR TITLE
Remove hairy cocks

### PR DESCRIPTION
**Pull request by colemclaren**
This is disgusting. These comments were left everywhere. Absolutely gross. Please fix.

### CODE REVIEW

**Comment by colemclaren** [comment]
I would like to add I made this same change 5 years ago and it was denied. How are we feeling about it now? Completely forgot about it. It ruins my day when I browse Garry's Mod base files and unexpectedly run into inappropriate words while I am trying to enjoy my programming session. This is not welcoming for women at all. This needs to change.

https://github.com/Facepunch/garrysmod/pull/1414/files#diff-510aa4217525f5a0ecb6f4df12c3adaf53802b84531ef39113de2a5156287d49

**Comment by Kefta** [comment]
Welcome back moat. I hope you're doing better.

**Comment by mechdabosh** [comment]
this is what i've been waiting for

**Comment by colemclaren** [comment]
I hate when I have to edit base Garry's Mod files, and when I see words like this it completely ruins my day. I do not want inappropriate words in my servers code. This does not need to exist, so please get rid of it.

**Review by robotboy655 — APPROVED** [review]

**Pull request merged**
