### PR TITLE
Update control.Menu.js

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by Kefta** [comment]
Why did you make this into a separate PR instead of merging into the original?

**Comment by MoskalykA** [comment]
Cause I don't know how to change the original.

**Comment by MoskalykA** [comment]
Yes

**Comment by Kefta** [comment]
You should close 3 of your PRs merge it into one. You can edit it by going to your garrysmod fork, changing the branch to the PR you're keeping, and editing there.

**Comment by MoskalykA** [comment]
Okey thanks

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/pull/1668

**Pull request closed without merging**
