### PR TITLE
Prevent duplicator from copying gmod_anchor

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes https://github.com/wiremod/advdupe2/issues/127

### CODE REVIEW

**Comment by robotboy655** [comment]
This would make duplicated hydraulics attached to the world unstable. There's a reason this hack exists.

**Comment by thegrb93** [comment]
Duped sliders create their own gmod_anchor. The duped gmod_anchor is just duped garbage. Not like I didn't test this or anything.

**Comment by robotboy655** [comment]
I cannot confirm that with the built-in duplicator and ```lua_run PrintTable(ents.FindByClass("gmod_a*"))```

**Comment by thegrb93** [comment]
Okay, I was testing this the 'fixed' hydraulic and it was generating garbage gmod_anchor. I'll add a fix to slider duplication so that it matches hydraulic duplication.

**Comment by robotboy655** [comment]
Yeah I was testing with "fixed" enabled as well. Perhaps try without mods? Or maybe the problem lies with how advdupe2 handles it?

**Pull request closed without merging**
