### PR TITLE
Update net.lua

### PR DESCRIPTION
**Pull request by KilgraveVlatkovic**

### CODE REVIEW

**Comment by willox** [comment]
I don't think this'll be a good idea. Lag compensation can be particularly expensive and I'm confident that not every net receiver in existence requires it.

**Comment by KilgraveVlatkovic** [comment]
Almost everything else in the game is lag compensated (PrimaryAttack for example), I don't see it creating too much more overhead.

**Comment by KilgraveVlatkovic** [comment]
I suppose you're right, after a benchmark it shows that implementing LagCompensation ups runtime by 3x.

**Comment by thegrb93** [comment]
Not to mention it could break a lot of things that don't expect this behavoir.

**Comment by neico** [comment]
If anything make it opt-in, there might be use cases, but those probably are by far the minority who actually benefit of off it.

**Pull request closed without merging**
