### PR TITLE
Added: Support for typing disable for text boxes

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by robotboy655** [comment]
Why?

**Comment by dvdvideo1234** [comment]
So you can be able to forbid the players to edit the text box, but to be allowed only to copy its contents.

**Review by robotboy655 — CHANGES_REQUESTED** [review]
It should at least be named `readonly` then, and affect all the other property types as well. 

Also please refrain from pointlessly modifying whitespace and comments.

**Comment by dvdvideo1234** [comment]
My IDE is automatically set to trim the trailing spaces.

**Comment by Kefta** [comment]
They aren't trailing though, they're separators

**Comment by dvdvideo1234** [comment]
Hello,  @robotboy655... Done ;)

**Review by robotboy655 — CHANGES_REQUESTED** [review]
I have tested it and it simply won't work this way.

I think however you can simply add
```
-- If the field is read only, disable it
if ( vars && vars.readonly ) then
	self:SetEnabled( false )
end
```

to `DProperties.lua` on line 65 and that should cover it for all property types, even addon ones.

**Comment by dvdvideo1234** [comment]
Should I remove the `prop_*.lua` changes then. I mean revert all the changes in prop_*.lua files ?

**Comment by robotboy655** [comment]
Yeah

**Pull request merged**
