### PR TITLE
Direct GM:AddDeathNotice call replaced by hook.Run

### PR DESCRIPTION
**Pull request by CornerPin**
This will allow to hide death notices by returning any value in the hook.

### CODE REVIEW

**Comment by Kefta** [comment]
Fixes https://github.com/Facepunch/garrysmod-issues/issues/2611

**Comment by CornerPin** [comment]
Should I change the use of [hook.Run](http://wiki.garrysmod.com/page/hook/Run) to [hook.Call](http://wiki.garrysmod.com/page/hook/Call)?

**Comment by YuRaNnNzZZ** [comment]
Any updates on this? It's still [listed as a hook on wiki](https://wiki.garrysmod.com/page/GM/AddDeathNotice).

**Comment by YuRaNnNzZZ** [comment]
this hook would be useful if someone wanted to do a **Half-Life** Deathmatch: **Source** killfeed addon

**Comment by robotboy655** [comment]
I know this is useful to people, but I still want to redo that system to be more dynamic which might include removing that internal method, so I'd rather not add it as a hook just yet.

If all you want is to hide the default killfeed, you could force `hud_deathnotice_time` to 0 or simply override one of the GM:* methods in that file, even tho that is less than ideal solution.

**Review by robotboy655 — APPROVED** [review]

**Pull request merged**
