### PR TITLE
Bring back hairy cocks

### PR DESCRIPTION
**Pull request by callumok2004**
Reverts #1901

### CODE REVIEW

**Comment by TheXnator** [comment]
bring back hairy cocks

**Comment by bludotbat** [comment]
The removal of this broke my entire codebase. Game is completely unplayable without this.

**Comment by callumok2004** [comment]
> The removal of this broke my entire codebase. Game is completely unplayable without this.

I completely agree, hence why I want this added back!

**Comment by imLiaMxo** [comment]
broke my game, this needs to be fixed.

**Pull request closed without merging**
