### PR TITLE
Add string.StartsWith

### PR DESCRIPTION
**Pull request by swampservers**
🇬

### CODE REVIEW

**Comment by CornerPin** [comment]
This was rejected in https://github.com/Facepunch/garrysmod/pull/1176.

**Comment by WilliamVenner** [comment]
Unreject it then

**Comment by Kefta** [comment]
I just thought about this today.

**Comment by garryspins** [comment]
shut up and merge this what are you waiting for

**Comment by NoSharp** [comment]
Worth while, 10/10 revolutionary!

**Comment by swampservers** [comment]
bump

**Comment by swampservers** [comment]
bump

**Comment by Kefta** [comment]
Bumping is just going to just make Rubat close this faster.

**Comment by WilliamVenner** [comment]
REMEMBER WHAT THEY TOOK FROM YOU

image

**Comment by robotboy655** [comment]
Goddamit

**Comment by NoSharp** [comment]
YES! GREAT SUCCESS!

**Pull request merged**
