### PR TITLE
Add checks to AddBackgroundImage

### PR DESCRIPTION
**Pull request by ThatGamingWolf**
Adds checks to AddBackgroundImage so that only valid backgrounds get added and removed a useless parameter for ClearBackgroundImages

### CODE REVIEW

**Comment by Kefta** [comment]
You should throw some errors instead of silently failing

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod/blob/0fa212127164b965d45fea781a73f4f6d762bd18/garrysmod/lua/menu/mainmenu.lua

These checks are pointless,

**Comment by ThatGamingWolf** [comment]
Im aware that by default this would never be an issue but some people do run their own menu lua and this would very easily error since neither the adding or use of the backgrounds gets checked beforehand, only checked for nil

**Comment by robotboy655** [comment]
Editing the menu state is not officially supported in mod form.

**Pull request closed without merging**
