### PR TITLE
Replaced Profanity

### PR DESCRIPTION
**Pull request by moat7**
promote a family-friendly environment for young learners

### CODE REVIEW

**Comment by meepdarknessmeep** [comment]
honestly this is what keeps minorities and women out of programming

**Comment by Jvs34** [comment]
this really triggers my feminism

**Comment by TrixterTheTux** [comment]
Thx moat

**Comment by MrUnknownGamer** [comment]
Aww someone needs a safe space. Do you sexually identify as a TransSDkjfds and don't have a "hairy cock"

**Comment by robotboy655** [comment]
Don't include TTT file changes with the rest of the file changes.

**Comment by SwadicalRag** [comment]
TTT changes being separate is what keeps minorities and women out of programming

**Comment by Linkfan123** [comment]
https://i.imgur.com/YtTNXjH.png

...just why

crap isn't a bad word

shit is

not crap

y u do dis to meh

**Comment by Linkfan123** [comment]
Also just so you know Garry's Mod is rated M. Or if it isn't, the original game it was based on, HL2, was rated M, plus you can play HL2 in Garry's Mod right out of the gate, which should classify it's M rating.

You don't need to make stuff family-friendly, because the game itself isn't in the first place.

If this is a troll though it's funny tnx

**Comment by Linkfan123** [comment]
also another change that makes no sense https://i.imgur.com/rvpq6ku.png

**Comment by Linkfan123** [comment]
But also thanks for showing how great this mod is by the random... shit in it.

oh no

**Comment by moatato** [comment]
https://twitter.com/garrynewman/status/1174699748605009921

**Comment by Kefta** [comment]
Hope you're doing well Moat

**Pull request closed without merging**
