### PR TITLE
Add table.HasKey, table.ValueFromKey

### PR DESCRIPTION
**Pull request by Zoephix**

### CODE REVIEW

**Comment by GitSparTV** [comment]
...
Have you heard about...

```lua
if tbl[key] then print("key exists") end
```?

**Comment by GitSparTV** [comment]
**Have you heard about**

```lua
print("Value: ", tbl[key])
```
?

**Comment by Zoephix** [comment]
Yeah we can do it even shorter, even this would probably work

function table.HasKey( t, key )
  return t[key] != nil
end

however considering the structure from the functions above (E.G table.HasValue) is done this way too I thought to stick with that to prevent it from becoming unorganized.

**Comment by GitSparTV** [comment]
That's pointless.
This should be always inlined

**Comment by Zoephix** [comment]
> That's pointless.
> This should be always inlined

"Pointless" in that case you may as well call all the GMod extensions "Pointless" considering you can always create them yourself, the extensions are there as basic help for those who can't figure out how to do it themselves, that if they didn't weren't included by default.

In other words the point you're trying to make is stupid, extensions exist for a reason.

**Comment by GitSparTV** [comment]
Compare this
```lua
local value = nil
if table.HasKey(tbl, 1) then
    value = table.VauleFromKey(tbl, 1)
end
```

And 
```lua
local value = tbl[1]
```

**Comment by Zoephix** [comment]
> Compare this
> 
> ```lua
> local value = nil
> if table.HasKey(tbl, 1) then
>     value = table.VauleFromKey(tbl, 1)
> end
> ```
> 
> And
> 
> ```lua
> local value = tbl[1]
> ```

That's the most retarded code I've seen in a while, that's not exactly how that works.

**Comment by SneakySqwuid** [comment]
this is a fuckin yeet

**Comment by GitSparTV** [comment]
Pointless is when people uses gmod functions without knowing they can use built-in Lua stuff.
My favorite example is `table.HasValue` instead of table sets, `table.Count` instead of `#tbl` and `table.Random` instead of `tbl[math.random(#tbl)]`.

**Comment by Mijyuoon** [comment]
> That's the most retarded code I've seen in a while, you're doing it wrong too. Lmao.

Are… are you actually fucking claiming that `t[k]` table accessor is "retarded" despite being the *very basic* Lua feature??

**Comment by Zoephix** [comment]
> Pointless is when people uses gmod functions without knowing they can use built-in Lua stuff.
> My favorite example is `table.HasValue` instead of table sets, `table.Count` instead of `#tbl` and `table.Random` instead of `tbl[math.random(#tbl)]`.

That's exactly the point of having extensions, because people don't think about how to do it themselves.

**Comment by GitSparTV** [comment]
Well if you don't know `tbl[key]` you are dumb as fuck don't use gmod before learning this

**Comment by viral32111** [comment]
Adding extensions for this is just going to complicate things in the future when new developers or addon creators come to create stuff, it's better that people learn the core Lua way of doing it as at least that way it's stack call.

**Comment by Mijyuoon** [comment]
> That's exactly the point of having extensions, because people don't think about how to do it themselves.

So instead of teaching people how to do this properly you'd rather do stupid shit that also has terrible performance?

**Comment by viral32111** [comment]
How is the core Lua way terrible performance?

**Comment by Zoephix** [comment]
> > That's exactly the point of having extensions, because people don't think about how to do it themselves.
> 
> So instead of teaching people how to do this properly you'd rather do stupid shit that also has terrible performance?

From what you're saying you may as well remove table.HasValue, table.KeyFromValue too.

**Comment by viral32111** [comment]
> From what you're saying you may as well remove table.HasValue, table.KeyFromValue too.

I imagine if those were going to be impleted today, it would be denied. Thing is, they can't be removed at this point, because hundreds of thousands of addons use them.

**Comment by GitSparTV** [comment]
Also, speaking of the speed.
tbl[key] os O(1) and it's the fastest way.
Your functions uses pairs which breaks JIT compilation and it will be slow as fuck

**Comment by Mijyuoon** [comment]
> How is the core Lua way terrible performance?

I was referring to this HasKey nonsense.

> From what you're saying you may as well remove table.HasValue, table.KeyFromValue too.

`table.HasValue` shouldn't have existed in the first place IMO. People use it indiscriminately when they should be using tables in set mode (`t[k] = true`)

**Comment by GitSparTV** [comment]
The performance is similar to `table.HasValue` versus `tbl[key]`. Identical actually

**Comment by Zoephix** [comment]
> > From what you're saying you may as well remove table.HasValue, table.KeyFromValue too.
> 
> I imagine if those were going to be impleted today, it would be denied. Thing is, they can't be removed at this point, because hundreds of thousands of addons use them.

That's entirely true, but they were once created with the reason of "People don't know how to do it themselves" too, basically helping noobs rather than having them figure it out themselves.

**Comment by GitSparTV** [comment]
Go learn lua noob

**Comment by Zoephix** [comment]
> Go learn lua noob

this was with the intention to help those who don't, I don't think you quite get my point

**Comment by viral32111** [comment]
> That's entirely true, but they were once created with the reason of "People don't know how to do it themselves" too, basically helping noobs rather than having them figure it out themselves.

I don't see how implementing `table.HasValue` magically gave creators the knowledge on how to use it. `tbl[key]` is written out in the Lua docs, which is something you should be paying attention to if you're coding Lua.

**Comment by GitSparTV** [comment]
I got your point, go learn lua and teach everyone to use `tbl[key]`
Also learn why pairs is bad compared to `[key]`

**Comment by Kefta** [comment]
> From what you're saying you may as well remove table.HasValue, table.KeyFromValue too.
rBTlkpG

**Comment by Zoephix** [comment]
Funny thing is if table.HasValue, table.KeyFromValue were to be removed a lot of people would probably come crying for help on the Garry's Mod Discord on how to fix it, this shows the exact reason of why the extensions were created, to prevent players from spamming everything 24/7 on help with basic things.

**Comment by GitSparTV** [comment]
If you have problems with getting a value or checking if the key exists you have big problems.

Learn Lua please

**Comment by Kefta** [comment]
> a lot of people would probably come crying for help on the Garry's Mod Discord on how to fix it

Good, that's called seeking out information instead of relying on useless extensions. Good habits and efficient idioms are key to knowing how to use the language you're writing in.

**Comment by Mijyuoon** [comment]
> Funny thing is if table.HasValue, table.KeyFromValue were to be removed a lot of people would probably come crying for help on the Garry's Mod Discord on how to fix it.

These are the kind of people who haven't learned even basics of Lua properly and most likely just copypaste stuff together until it sorta works.

**Comment by viral32111** [comment]
> Funny thing is if table.HasValue, table.KeyFromValue were to be removed a lot of people would probably come crying for help on the Garry's Mod Discord on how to fix it, this shows the exact reason of why the extensions were created, to prevent players from spamming everything 24/7 on help with basic things.

Yes, they would. Why? because they were added in the first place, so people never learned the real and better way to do it.

If they were never added however many years ago and it was suggested today, I again doubt it would be added because *hopefully* people would've learned the core Lua way of doing it.

**Comment by Zoephix** [comment]
> If you have problems with getting a value or checking if the key exists you have big problems.
> 
> Learn Lua please

I'm not having problems with that, I'm just saying there's people who do.

**Comment by GitSparTV** [comment]
If they have problems we are happy to help them!

**Comment by GitSparTV** [comment]
tbl[key] is Tables 101 what the fuck.
You are over-engineering indexing

**Comment by viral32111** [comment]
I'm guessing table.HasValue and table.KeyFromValue were added years and years ago, at which point the addon creator community may have been smaller and thus support was harder to come by, so I can kind of understand why they were added back then to help people and make it more obvious if they hadn't come from a background of programming in other languages. 

But today, with how big the addon creator community is, there is no reason for stuff like this to be added as support is easy to come by and people have learned (and documented) the best ways of doing it already.

**Comment by VladUndying** [comment]
fG0QyQPbW7o

**Comment by Fafy2801** [comment]
This is just stupid, if this were to be added, some people would actually use it and thus create addons that lag everything because they are looping tables instead of using the fucking tbl[k]

**Comment by Zoephix** [comment]
Like I said on my first reply I would've done

function table.HasKey( t, key )
return t[key] != nil
end

instead as extension function, but I thought to keep the structure from above because I wasn't sure if they intended to keep their way of doing that.

**Comment by viral32111** [comment]
> This is just stupid, if this were to be added, some people would actually use it and thus create addons that lag everything because they are looping tables instead of using the fucking tbl[k]

Exactly. We don't need to add more unoptimised functions to the game just to help the people who don't understand array/tables. If they don't understand it then they can come get support or look at the various wiki/documentation websites ran by the community for assistance.

**Comment by VladUndying** [comment]
nO yOu CaNt RoAsT mE, iM dOiNg It DiFfErEnT wAy ThIs Is WhY yOu MaD

**Comment by GitSparTV** [comment]
_p o i n t l e s s_
_f u n c t i o n_
_o v e r h e a d_

**Comment by Zoephix** [comment]
Apparently the way of doing it doesn't matter, also the existing functions were added a long time ago. Closing this here because I suppose the extensions are unnecessary nowadays.

**Comment by Zoephix** [comment]
Just in case anyone looking for this shit comes across this because of a Google Search here you go:

```
function table.HasKey( tbl, key )
	return tbl[key] != nil
end

function table.ValueFromKey( tbl, key )
	return tbl[key]
end
```

tbh you don't even need to use the functions, just pull a _tbl[key]_ or _tbl[key] != nil_ whenever you need that

**Comment by DBotThePony** [comment]
is this a shitpost

**Pull request closed without merging**
