### PR TITLE
concommand.Exists( name ) & little improvements

### PR DESCRIPTION
**Pull request by PrikolMen**
I tweaked the console command module, simplified the localization and added a new `concommand.Exists( name )` method.

### CODE REVIEW

**Comment by Kefta** [comment]
Please change the table names back, lower camel case is not a standard in this codebase.

**Comment by robotboy655** [comment]
As a rule of thumb - do not include unnecessary changes to your Pull Requests.

**Comment by PrikolMen** [comment]
> Please change the table names back, lower camel case is not a standard in this codebase.

Explain to me then what happens in this file:
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/cleanup.lua#L3

I'll fix it, but if you're demanding something like this, either fix it all in one true format, or don't demand anything.

**Comment by PrikolMen** [comment]
Any smallest change requires so much effort. With developers like you, the game will die. Doing nothing yourself, and demanding that the community fixes and develops the game, you disgust me.

**Comment by Kefta** [comment]
> > Please change the table names back, lower camel case is not a standard in this codebase.
> 
> Explain to me then what happens in this file: https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/cleanup.lua#L3
> 
> I'll fix it, but if you're demanding something like this, either fix it all in one true format, or don't demand anything.

That's snake case, not lower camel, which is used mixed with upper camel across the codebase.

> Any smallest change requires so much effort. With developers like you, the game will die. Doing nothing yourself, and demanding that the community fixes and develops the game, you disgust me.

Sorry, I'll do more.

**Pull request closed without merging**
