### PR TITLE
Fix gmod_camera being dependent on tickrate

### PR DESCRIPTION
**Pull request by DBotThePony**
This bothers me for insanely long time

### CODE REVIEW

**Comment by thegrb93** [comment]
Multiply the existing magic numbers with 66. Would look better

**Comment by thegrb93** [comment]
`* 6.6`
`* 1.65`

**Comment by DBotThePony** [comment]
If you are so nervous about performance of Division vs Multiplication even in non performance critical function then ok

**Comment by robotboy655** [comment]
It's less about performance and more about readability/"niceness" of code.

**Comment by GitSparTV** [comment]
Not to mention, such expressions are evaluated at compile time, so it doesn't matter

**Comment by robotboy655** [comment]
Also is it really necessary to replace tabs with spaces for no reason?

**Comment by thegrb93** [comment]
> Not to mention, such expressions are evaluated at compile time, so it doesn't matter

Lua doesn't optimize division by constant unless you do `* (1/constant)`

**Comment by GitSparTV** [comment]
> `* 6.6`
> 
> `* 1.65`

Ah I thought you mentioned this because the code had `smth * 6.6 * 1.65`.
Nvm then

**Comment by DBotThePony** [comment]
> Also is it really necessary to replace tabs with spaces for no reason?

because it is done automatically on save to avoid obvious github editor and other editors issues when tab width is not 4 spaces (which is obviously the case with Garry's code editor preferences)

**Comment by Kefta** [comment]
I think the constants should be multiplied by 66 to conserve their initial values.

**Review by thegrb93 — APPROVED** [review]

**Pull request merged**
