### PR TITLE
Remove ping from serverlist score system

### PR DESCRIPTION
**Pull request by meepen**
Ping no longer matters with A2S Info anycast "protection"

### CODE REVIEW

**Comment by robotboy655** [comment]
No, we won't be fucking everyone (including players) because some servers are using anycast,

**Comment by meepen** [comment]
Can you solve the issue then as to avoid giving people distinct advantages by abusing this feature?

**Comment by robotboy655** [comment]
There is no solving it.

**Comment by meepen** [comment]
So you won't remove them from the list, you won't try to fix it, and you will continue to allow people with more money dominate the serverlist unfairly and have your players be intentionally misled on the server list inside your own game?

This will literally kill off this game by making no new developers come to the game to make servers. The game is going to continue to decline in player count due to a monopolized server list controlled by people with tons of money to spend by creating gambling-like addictions on this game's players.

This really needs to be dealt with...

**Comment by Kefta** [comment]
Do you have any ideas of how to remedy it?

**Comment by meepen** [comment]
- Blacklist the servers
- Rework the serverlist to not be 100% biased to servers with ping at 10 (around the world)
- Enforce a standard that these people using this for "protection" to make it also add a timeout to the packets before replying to give a real ping estimate

Hell, I'd write you guys a program to detect ping spoofing to automatically update the blacklist if you'd let me, by just having two or three different servers around the world.

**Comment by meepen** [comment]
Also it kind of urks me that I had to make this kind of issue to even get a response from the developers on this issue, given that I've emailed rubat twice, and tried to reach out to garry as well.

**Comment by ThatLing** [comment]
You can implement ``sv_setsteamaccount`` like CS:GO does so server owners have to link their steam account to a server. Their account can be banned from this system if they absue the server browser.

**Comment by Kefta** [comment]
@meepen Adding a timeout to packets defeats the purpose of the DDoS protection aspect of anycast, but a field could be added to Source server queries that allow the servers to report the correct ping without a delay. Rubat said he'd also thought of this solution, but enforcement would have to be stronger for it to have any widespread adoption.

**Comment by thegrb93** [comment]
Ping is no longer reliable? Lame

**Comment by innocentmoat** [comment]
@meepen font size of server list?

**Comment by innocentmoat** [comment]
font size of server list? @meepen

**Pull request closed without merging**
