### PR TITLE
Optimizations using table.IsEmpty

### PR DESCRIPTION
**Pull request by WilliamVenner**
1. Replaced `table.Count( .. ) == 0` with `table.IsEmpty( .. )`
2. Replaced `table.Count( .. ) > 0` with `not table.IsEmpty( .. )`

### CODE REVIEW

**Comment by willox** [comment]
did you test it? table.Empty is not table.IsEmpty

**Comment by WilliamVenner** [comment]
Oops, my bad.

**Comment by Kefta** [comment]
I'm gonna predict the future and say you should separate out the TTT changes to another PR. Tested on Sandbox and everything is working.

**Comment by WilliamVenner** [comment]
Ah yes good point... let me do that now.

**Comment by WilliamVenner** [comment]
#1569

**Comment by neico** [comment]
Shouldn't `not` be `!`?
That's what is commonly used across the code at least

**Comment by WilliamVenner** [comment]
Fixed again for `not`/`!` style.

**Pull request merged**
