### PR TITLE
The code has become simpler and better.

### PR DESCRIPTION
**Pull request by johngetman**

### CODE REVIEW

**Comment by WilliamVenner** [comment]
This unnecessarily creates new `Color` objects that the GC must free.

**Review by GitSparTV — CHANGES_REQUESTED** [review]
This is in no way better.
Creating a colour structure is an overhead. SetTextColor also has an overhead to read table, you also made not a white color. Why is it 255,0,255?

`color` is unpacked on purpose, you packed it back.

**Comment by GitSparTV** [comment]
You also create new Color's, not even localising default white colour

**Comment by robotboy655** [comment]
Yeah, and this is a code style change at best which is pointless.

**Pull request closed without merging**
