### PR TITLE
Update control.Menu.js

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by Kefta** [comment]
We should have a link for the Discord as well.

**Comment by MoskalykA** [comment]
> We should have a link for the Discord as well (discord.gg/gmod).

I couldn't agree more. I'll make it a proposal.

**Comment by MoskalykA** [comment]
I made the proposals.

Links: 
- https://github.com/Facepunch/garrysmod/pull/1670
- https://github.com/Facepunch/garrysmod/pull/1669

**Comment by robotboy655** [comment]
Please use proper methods of proposing changes into a GitHub repository. Create 1 Pull request, not 4.

I also still am not convinced we need a button to make a picture of the main menu.

Or a link to the wiki or to the Discord server for that matter.

**Comment by viral32111** [comment]
> I also still am not convinced we need a button to make a picture of the main menu.

I think he may have meant a button that appeared in the esc menu (when playing on a server or in singleplayer) that took a screenshot as if the menu wasn't there, although I don't really see a need for even that considering there's a number of ways to take screenshots...

* Camera (The sandbox weapon)
* `jpeg` console command.
* `poster` console command.
* F12/F5 (Steam's screenshot thing)

It might've been suggested because in a situation where the player doesn't have the Camera, there's no clear indication as to how they can take a screenshot? 🤔

**Pull request closed without merging**
