### PR TITLE
Update kb_act.lst (LOCALIZATION)

### PR DESCRIPTION
**Pull request by BreakinBenny**
#Valve_Console_Toggle, whitespaces left alone.

### CODE REVIEW

**Comment by Kefta** [comment]
You could have just updated your previous PR

**Comment by BreakinBenny** [comment]
The problem is that I don't know how to edit pull requests.

**Comment by neico** [comment]
Commit-push changes to the branch you made the PR in,  
you *could* even force-push it if you care about commit history,  
not that the one to accept the PR can do a squash anyway.

The PR itself is only this discussion board and a diff reference from your selected branch to the selected target branch (usually master) which you can modify outside git's system

**Comment by BreakinBenny** [comment]
I still think it's kinda odd you guys didn't think to do the #Valve_Console_Toggle idea in the first place, requiring the community to help out with the issue… At least I am helping.

**Comment by Kefta** [comment]
You're acting as if you just solved a major bug plaguing GMod - it was a small negligible oversight that was probably caused by Valve not including it in the localisation files when they were first copied to this game. All we suggested above and in your other pulls were ways you could improve PR usage in the future.

**Pull request merged**
