### PR TITLE
TTT: Remove ASS

### PR DESCRIPTION
**Pull request by colemclaren**
Inappropriate comment. Not necessary.

### CODE REVIEW

**Comment by Kefta** [comment]
Replace it with something that at least conveys its hacky nature.

**Comment by colemclaren** [comment]
> Replace it with something that at least conveys its hacky nature.

I'd rather just replace the hacky nature all together. It's not really hacky if you read it. All it does is extend the width of the panel in case the label is too long. I don't think it's hacky for what it does. What do you propose it be changed to?

**Comment by colemclaren** [comment]
Perhaps a new pull request should be made for fixing the hacky nature? I only want to remove the awful comment. Nothing else.

**Comment by colemclaren** [comment]
> > Replace it with something that at least conveys its hacky nature.
> 
> I'd rather just replace the hacky nature all together. It's not really hacky if you read it. All it does is extend the width of the panel in case the label is too long. I don't think it's hacky for what it does. What do you propose it be changed to?

I take this back. It's in a think hook. I've replaced the comment with a better way of conveying the message across. I appreciate the idea thank you.

**Pull request merged**
