### PR TITLE
Update soundscapes_manifest.txt

### PR DESCRIPTION
**Pull request by BreakinBenny**
Added soundscapes for Zombie Panic: Source. (I hope one day ZPS animations in Source Filmmaker will be a thing!)

### CODE REVIEW

**Comment by robotboy655** [comment]
First of all, you should put all relevant files to this Pull Request (PR) into one PR, not into multiple.
Secondly, I cannot merge this because this is content from another retail game and we will need an explicit permission from the game's developers to do this.

**Comment by BreakinBenny** [comment]
Here's what JonnyBoy0719 says in the Discord chat, today at 6:13 PM:

_Since ZPS is F2P, and anyone can play it, and if you mount it within Gmod, I don't see the issue where you cannot use the soundscapes from ZPS
also, the soundscapes will be updated in 3.0.8, just keep that in mind :smiley:_

And my replies, at 6:22 PM:
_I guess I can wait with it, then. I've already inserted the soundscapes into a custom manifest for use in GMOD.
Robotboy655 might be pleased, but in this case I'll hold it back until further notice._

**Comment by mcNuggets1** [comment]
Is this the developer of zps?

**Comment by BreakinBenny** [comment]
One of them. I was asked to talk about it in the Discord chat when I spoke on their forums.

**Pull request closed without merging**
