### PR TITLE
Add more NPCs categorized as hostile and friendly towards players

### PR DESCRIPTION
**Pull request by FlorianLeChat**
It's all in the title. These NPCs are hostile and friendly towards players by default in Garry's Mod but also in Half-Life 1/2.

### CODE REVIEW

**Comment by robotboy655** [comment]
Should probably also have the HL1 npc classnames here as well

**Comment by FlorianLeChat** [comment]
Let me know if it's good for you!

**Comment by robotboy655** [comment]
You should do the same for the friendly types as well.

**Review by robotboy655 — CHANGES_REQUESTED** [review]
You should do the same for the friendly types as well.

**Comment by FlorianLeChat** [comment]
It wasn't the original purpose of this pull request, but obviously it made more sense in this way.

**Pull request merged**
