### PR TITLE
Update dcheckbox.lua

### PR DESCRIPTION
**Pull request by johngetman**

### CODE REVIEW

**Comment by mcNuggets1** [comment]
wtf

**Comment by ZH-Hristov** [comment]
Replace the not with a !
Does the same thing

**Comment by mcNuggets1** [comment]
This is a very irrelevant request.

**Comment by Kefta** [comment]
It's not irrelevant because GMod uses C-styled ops in the codebase.

**Review by robotboy655 — APPROVED** [review]

**Pull request merged**
