### PR TITLE
New askconnect dialog

### PR DESCRIPTION
**Pull request by WilliamVenner**
https://i.venner.io/TgAwZfl7BM.mp4

https://i.venner.io/PmpMr7hKev.mp4

### CODE REVIEW

**Comment by NoSharp** [comment]
Looks really cool!

**Comment by TomDotBat** [comment]
Much prefer this solution over the current :)

**Comment by shadow7483147** [comment]
Hard pass. Client connects should never be automatic. The askconnect dialog was added for this exact reason, because servers were abusing automatic connections.

**Comment by WardenPotato** [comment]
My main concern regarding this is that if the redirect is automatic it will get abused by larger servers to put all their afks in their less popular servers, which is unfair to other communities and misleading in the server browser

**Comment by WilliamVenner** [comment]
How about pausing the timer if the mouse hasn't moved since the dialog has been opened?

Some kind of hack would have to be implemented to stop input.SetCursorPos and stuff from triggering it.

**Comment by robotboy655** [comment]
As already mentioned, this defeats the purpose of the askconnect dialog. The only solution to the "IT RUINS EVERYTHING!!!11" argument is ability for the player to consciously save their choice for future popups from the same server.

**Comment by WilliamVenner** [comment]
Was hoping to have an actual discussion, but alright.

**Comment by MrCreamie** [comment]
hot, like always billy.

**Pull request closed without merging**
