### PR TITLE
math.Clamp efficiency

### PR DESCRIPTION
**Pull request by Threebow**

### CODE REVIEW

**Comment by Kefta** [comment]
This would be less efficient from two function calls.

**Comment by Kefta** [comment]
I find it hard to believe the branch predictability cost is lower than two additional function calls.

**Comment by notcake** [comment]
There are no function calls.
LuaJIT inlines math.min and math.max into maxsd and minsd x86 instructions.

**Comment by Kefta** [comment]
@thegrb93 https://facepunch.com/showthread.php?t=1584849

**Comment by thegrb93** [comment]
```lua
require 'xbench'

function math.NewClamp( _in, low, high)
	return math.min( math.max( _in, low ), high )
end

xbench.Compare({
    Old = function()
        math.Clamp(5, 0, 1)
        math.Clamp(0.5, 0, 1)
        math.Clamp(-2, 0, 1)
    end,
    New = function()
        math.NewClamp(5, 0, 1)
        math.NewClamp(0.5, 0, 1)
        math.NewClamp(-2, 0, 1)
    end,
}, 100000000)
```
] lua_openscript testclamp.lua
Running script testclamp.lua...
OLD: 0.057845269812219
NEW: 0.053289889537041
] lua_openscript testclamp.lua
Running script testclamp.lua...
OLD: 0.055786881494896
NEW: 0.052753483020069
] lua_openscript testclamp.lua
Running script testclamp.lua...
OLD: 0.05760076262095
NEW: 0.053545263714568

**Comment by thegrb93** [comment]
```lua
require 'xbench'

function math.NewClamp( _in, low, high)
	return math.min( math.max( _in, low ), high )
end

local a, b = -1, 1

xbench.Compare({
    Old = function()
		for i=a, b do
			math.Clamp(i, -0.5, 1)
			math.Clamp(i, -0.5, 1)
			math.Clamp(i, -0.5, 1)
		end
    end,
    New = function()
		for i=a, b do
			math.NewClamp(i, -0.5, 1)
			math.NewClamp(i, -0.5, 1)
			math.NewClamp(i, -0.5, 1)
		end
    end,
}, 100000000)
```
] lua_openscript testclamp.lua
Running script testclamp.lua...
OLD: 0.057974466204541
NEW: 15.501502058992

**Comment by thegrb93** [comment]
```lua
require 'xbench'

function math.NewClamp( _in, low, high)
	return math.min( math.max( _in, low ), high )
end

local a, b = -0.5, 1.5

xbench.Compare({
    Old = function()
		for i=a, b do
			math.Clamp(i, 0, 1)
		end
    end,
    New = function()
		for i=a, b do
			math.NewClamp(i, 0, 1)
		end
    end,
}, 100000000)
```
OLD: 0.055306319212832
NEW: 0.05354798046119

**Comment by robotboy655** [comment]
Still has that extra parenthesis

**Comment by Kefta** [comment]
It is - just manually merge it.

**Pull request merged**
