### PR TITLE
Add CompoundLerp

### PR DESCRIPTION
**Pull request by LeQuackers**
Allows you to lerp variables smoothly every frame regardless of FPS/tick rate in Think/Render hooks, for example:

```Lua
-- after 1 second self.Var will be 95% from its initial position to 8
self.Var = CompoundLerp( 0.95, FrameTime(), self.Var, 8 )

-- after 3 seconds self.Var will be 65% from its initial position to 8
self.Var = CompoundLerp( 0.65, 0.33 * FrameTime(), self.Var, 8 )
```

### CODE REVIEW

**Comment by LeQuackers** [comment]
CompoundLerp doesn't fit too well in my opinion, anyone have a better name?

**Comment by GitSparTV** [comment]
isn't this math.Approach? 🤔

**Comment by GitSparTV** [comment]
Nvm you just using Lerp wrong ahahaha

**Comment by thegrb93** [comment]
Not wrong, but it's equivalent to `Lerp( 1 - ( 1 - t ) ^ delta, from, to )` so just use that instead.

**Comment by GitSparTV** [comment]
Could be added as example on wiki. So it won't be forbidden

**Comment by LeQuackers** [comment]
It's a math function. Saying someone is using Lerp wrong when it's common to do or gives the desired output is dumb.

The reason this pull request exists is because people use ```current = Lerp(FrameTime(), current, target)``` for smoothing, which is normally fine but sucks as the frame time approaches 1.

You can use ```Lerp( 1 - ( 1 - t ) ^ delta, from, to )``` if you want, but most people don't know how to fix the previously stated issue, hence this pull request.

**Comment by GitSparTV** [comment]
You still use Lerp wrong, you are passing the output value to `from` parameter, this makes lerp non-linear

**Comment by LeQuackers** [comment]
that's the point

**Comment by Kefta** [comment]
Then it's non-linear interpolation. Don't use lerp for this.

**Comment by LeQuackers** [comment]
That's why this pull request exists; to replace ```current = Lerp(FrameTime(), current, target)``` with an actual function.

**Comment by GitSparTV** [comment]
It won't be called lerp

**Comment by GitSparTV** [comment]
Also there is a similar function I mentioned earlier: math.Approach

**Comment by robotboy655** [comment]
Just use a more appropriate math function + `math.Remap` from a website like this: https://easings.net/ for the desired effect.

This way you will not end up with a forever changing number that will never reach the `to` value, and you won't have any issues with with frame time, since you'd wouldn't be using `FrameTime()`.

Here's an example adapted from that website and the example from Wiki's Lerp page:
```

function easeOutCubic( x )
	return 1 - math.pow( 1 - x, 3 )
end

function easeOutCubicRemapped( t, from, to )
	local t = math.Clamp( t, 0, 1 )
	local y = easeOutCubic( t )
	return math.Remap( y, 0, 1, from, to )
end

local start, oldhp, newhp = 0, 0, 0
local animationTime = 0.5

hook.Add("HUDPaint", "EaseOutExample", function()
	local hp = LocalPlayer():Health()
	local barW = ScrW() - 200 

	if newhp ~= hp then
		oldhp = newhp
		start = SysTime()
		newhp = hp
	end

	local smoothHP = easeOutCubicRemapped( (SysTime() - start) / animationTime, oldhp, newhp)

	draw.RoundedBox( 4, 100, 200, barW, 100, color_black )
	draw.RoundedBox( 4, 100, 200, math.max( 0, smoothHP ) / LocalPlayer():GetMaxHealth() * barW, 100, color_white )
end)
```

**Pull request closed without merging**
