### PR TITLE
Add util.Spring

### PR DESCRIPTION
**Pull request by LeQuackers**
Allows you to calculate spring movement regardless of FPS/tick rate without spazzing and add instantaneous velocity at different times. Also supports vectors, angles, and integers.

### CODE REVIEW

**Comment by LeQuackers** [comment]
This still feels like it's missing something, any suggestions?

**Comment by Kefta** [comment]
Maybe support dampening states?

**Comment by LeQuackers** [comment]
By dampening states do you mean something similar to Lerping between rates of decay? If I update the position and velocity when the rate of decay changes it might work, gonna have to test it.

**Comment by Kefta** [comment]
Yeah, the damping coefficient will cause the decay to affect the spring faster or slower

**Comment by LeQuackers** [comment]
RIP last comment. Lerping rate of decay is effected by FPS/tick rate. I could still try to make Lerping velocity and rate of decay work if I made it into a calc 3 problem, but I'm lazy, so I'll probably add functions similar to AddVelocity/AddVelocityAtTime for the rate of decay in the meantime.

**Comment by LeQuackers** [comment]
Added/Removed/Renamed stuff. Still need to figure out a good way to allow people to use different variables for time with this, like UnPredictedCurTime or a custom time system. Might let util.Spring have an optional function parameter that gets called instead of CurTime.

**Comment by GitSparTV** [comment]
Does it have a purpose in GMod? Looks very auxiliary

**Comment by Kefta** [comment]
What Spar said. This can be library implemented.

**Pull request closed without merging**
