### PR TITLE
Add convar that allows players to disable viewing custom sv_loadingurls

### PR DESCRIPTION
**Pull request by bmwalters**
Fixes Facepunch/garrysmod-requests#653
The convar name and help text are whatever; they can be changed if someone has a better suggestion.

### CODE REVIEW

**Comment by uRandomAlex** [comment]
Also add a convar that changes volume of all HTML panels (including loadingurls), like "volume" convar but not globally, only for Awesomium.

**Comment by Kefta** [comment]
Can this please be added? I've already modified my own base game to completely remove custom loading screens -- even if there is a better solution in the works, this should be accepted in the mean-time.

**Comment by mcNuggets1** [comment]
How about an convar to remove loadingscreen music? 🗡

**Comment by bmwalters** [comment]
@mcNuggets1 dunno if I can do that in Lua, maybe I could inject JS to the screen to mute HTML5 audio elements, but it might not work/fix everything/be good

**Comment by meepdarknessmeep** [comment]
https://facepunch.com/showthread.php?t=1439957

**Comment by bmwalters** [comment]
@meepdarknessmeep does that work with flash objects? iirc those can play audio on the loading screen as well

**Comment by bmwalters** [comment]
@robotboy655 This PR has quite a bit of positive community support. Are there any changes you would like to see made here?

**Comment by Linkfan123** [comment]
+support

You could also add a command that disables sound from custom loading screens. I can't tell you how many times i've tried to join a server and had to listen to crappy EDM while downloading 50 addons.

It could work like this:
`gmod_loadingscreen [0 1]: Disables custom loading screens`
'gmod_loadingscreen_sound [0 1]: Mutes custom loading screens`

**Comment by MrUnknownGamer** [comment]
+support

I've taken this code and bundled with a GMod 10 loading screen. When I disable custom loading screens, GMod 10 shows. Either way, +1 this needs to be added.

**Comment by robotboy655** [comment]
Resolve the conflicts and I will merge it.

**Comment by mcNuggets1** [comment]
It's been so long.

**Pull request merged**
