### PR TITLE
Fixed holstered invisibility hack

### PR DESCRIPTION
**Pull request by Leystryku**
why change the FOV to get invisibility while having a crowbar as model if holstered should just be no model at all.

### CODE REVIEW

**Comment by Kefta** [comment]
I'm pretty sure this will spam the console with MOD_STUDIO errors because of the viewmodel not being a valid model.

**Comment by mcNuggets1** [comment]
couldnt we just return true in PreDrawViewModel?

**Comment by Kefta** [comment]
@mcNuggets1 That doesn't work in ``SWEP:PreDrawViewModel``. The best solution would be to run ``self:GetOwner():GetViewModel():SetWeaponModel("")`` in SWEP:Deploy to just have no viewmodel attached while the weapon is active.

**Comment by mcNuggets1** [comment]
https://github.com/FPtje/DarkRP/blob/master/entities/weapons/keys/shared.lua#L59-L61

It's used in DarkRP for example and I am using it in some of my scripts and it works just fine.
I am not a source engine pro, just a hobby dev, but it seems to do something atleast.

**Comment by Kefta** [comment]
It seems you're correct - the wiki doesn't have the return documented. I will correct that.

**Comment by Leystryku** [comment]
there the spam should be gone now

**Comment by mcNuggets1** [comment]
Just to mention it, there are a few more weapons in ttt using v_crowbar for invisibility.
Healthstation for example.

You might wanna do them too.

Side note:
World model should be able to be "" without erroring, atleast from my tests.

Also there is no PreDrawWorldModel in the wiki.

DrawWorldModel seem to be the only hook for this.

**Comment by Kefta** [comment]
You can use DrawModel and DrawModelTranslucent for the world model. You can also set the models to empty strings again without spam.

**Comment by FlorianLeChat** [comment]
Any news? (normally pull requests for the TTT gamemode are quickly merged but I think this one has been forgotten over the years..)

**Comment by svdm** [comment]
It was left unmerged in expectation of a change from the non-existent PreDrawWorldModel to a DrawWorldModel approach etc as suggested (or just leaving the worldmodel-disabling in Deploy in place). Don't think that's about to happen so I'll close it now, new PR with a fully working solution is welcome.

**Pull request closed without merging**
