### PR TITLE
player.GetByAccountID( ID )

### PR DESCRIPTION
**Pull request by edgarasf123**

### CODE REVIEW

**Comment by VigiFyre** [comment]
For the love of god, for what inconceivable reason this is not merged for 1.5 years?

**Comment by BreakinBenny** [comment]
@VigiFyre Maybe God disapproves of what edgarasf123 has created?

**Comment by BreakinBenny** [comment]
There needs to be a sympathy emoji on Github, since (New) Facepunch now has it.

**Comment by Noiwex** [comment]
God has left us

**Comment by Noiwex** [comment]
@robotboy655

**Comment by BreakinBenny** [comment]
[YES!](https://www.youtube.com/watch?v=1W3UIVe0ABs)

**Pull request merged**
