### PR TITLE
Fix anticheat thing

### PR DESCRIPTION
**Pull request by Velkon**
Idk why it exists but now it's super unbypassable ****

### CODE REVIEW

**Comment by Tenrys** [comment]
Isn't LocalPlayer() NULL until some time after init?

**Comment by Kefta** [comment]
Until InitPostEntity, yeah.

**Comment by Tenrys** [comment]
So this won't work, correct?

**Comment by bull29** [comment]
it won't.

**Comment by Velkon** [comment]
I wrote this on my phone but I'll fix it when I get home unless someone wants 2 do it

**Comment by thegrb93** [comment]
Just add `local LocalPlayer = LocalPlayer` next to `local gmod_GetWeapons = plymeta.GetWeapons`. I still don't see the point though.

**Comment by Velkon** [comment]
Web editor is shit on phone

**Comment by Kefta** [comment]
This should probably be fixed internally, too.

**Comment by Velkon** [comment]
There are legitimate uses for getweapons, unless you mean LocalPlayer being nil

**Comment by Kefta** [comment]
What's the use of GetWeapons working for other players clientside? And LocalPlayer is never nil, it's null which means it can still be evaluated as invalid.

**Comment by Velkon** [comment]
You can still get a weapon list without getweapons but I guess it would only save on networking if you ever need to use it client-side

**Comment by Kefta** [comment]
I'm surprised they're networked at all to the local client. I would think that since the weapon is dormant when its holstered, the server wouldn't network anything about it to non-owning clients.

**Pull request merged**
