### PR TITLE
Allow for custom tooltip panels

### PR DESCRIPTION
**Pull request by PatrickRatzow**
This allows for Tooltip to be a custom panel if you do PANEL:SetTooltipPanel( panel ) on it.

If no panel are set it will just default to DToolTip.

Very neat if you switch between several different tooltips for different menus.

### CODE REVIEW

**Comment by Kefta** [comment]
The code would probably look better as Tooltip = vgui.Create( Panel or "DToolTip" ); probably just a personal preference, though

**Comment by PatrickRatzow** [comment]
I'd do that myself but I don't see Garry do that in his code and I want the coding style to be like his, consistency is key.

**Comment by Kefta** [comment]
Fair enough

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Panel/SetTooltipPanel is used for a different purpose.

**Pull request closed without merging**
