### PR TITLE
TTT: fix "select language" string

### PR DESCRIPTION
**Pull request by LetsTwist**
"It may be best to leave this next one english"

### CODE REVIEW

**Comment by Kefta** [comment]
I think you should do what the Chinese file did and leave the translated version, but put ``(Select Language)`` at the end.

**Comment by LetsTwist** [comment]
may i paste translate in german and portuguese versions from google translator if there is a verified translation?
Снимок1
Снимок2

**Comment by mcNuggets1** [comment]
It's "Sprache auswählen" aka "Sprache selektieren", but the first one is more popular.

**Comment by Kefta** [comment]
``Selecione o idioma`` for Portuguese is correct.

**Comment by LetsTwist** [comment]
@Kefta it's done i guess

**Comment by Perkzitos** [comment]
> `Selecione o idioma` for Portuguese is correct.

"Selecionar idioma" is better.

**Comment by Kefta** [comment]
I thought the intention was "Select a language", not literal "Select language", it sounds incorrect saying it.

**Comment by Perkzitos** [comment]
> I thought the intention was "Select a language", not literal "Select language", it sounds incorrect saying it.

In Portuguese, the way it will be written depends entirely on the context. Writing imperatively in a settings interface is strange, at least in Portuguese.

**Comment by Kefta** [comment]
I guess it's best to leave the verbs unconjugated for consistency.

**Pull request merged**
