### PR TITLE
Add string.CardinalToOrdinal

### PR DESCRIPTION
**Pull request by DELIBURD**
This would be a useful function to have for anyone who would want to use it.

Example:
`print( string.CardinalToOrdinal( 111 ) )`

Output:
`111th`

### CODE REVIEW

**Comment by Kefta** [comment]
You could more optimally implement this by caching the modulo results - would help in performance variant environments, like using this function multiple times in a HUD per frame.

```
function string.CardinalToOrdinal( cardinal )
	local basedigit = cardinal % 10

	if ( basedigit == 1 ) then
		if ( cardinal % 100 == 11 ) then
			return cardinal .. "th"
		end

		return cardinal .. "st"
	end

	if ( basedigit == 2 ) then
		if ( cardinal % 100 == 12 ) then
			return cardinal .. "th"
		end

		return cardinal .. "nd"
	end

	if ( basedigit == 3 ) then
		if ( cardinal % 100 == 13 ) then
			return cardinal .. "th"
		end

		return cardinal .. "rd"
	end

	return cardinal .. "th"
end
```

**Comment by willox** [comment]
Is this the same as STNDRD?

**Comment by DELIBURD** [comment]
@Kefta I will change it so it caches the modulo request. And @willox, it's similar to STNDRD, but it keeps the number prepended to the suffix. Kefta's way of doing it is more efficient than just doing 

`cardinal .. STNDRD(cardinal)`

Also, not too many people know about STNDRD considering its odd name.

**Review by robotboy655 — APPROVED** [review]

**Comment by Kefta** [comment]
Believe it or not I benchmark my code before claiming efficiency.

**Pull request merged**
