### PR TITLE
Added utf8.sub and utf8.idx

### PR DESCRIPTION
**Pull request by Donkie**
This is a WIP proposal sort of really. I admit I don't know a lot about UTF-8 but I was fixing up this chatbox which had really poor UTF-8 support and I figured that a simple string.sub and str[idx] would be really dandy. After some tinkering this is what I came up with, and the replacement worked perfectly. I thought other people could have use of this aswell, as the utf8 library is much of a mystery to most people. These functions are intended to remove that mystery so we (the people) get more UTF-8 support!

I'm gladly accepting criticism on if/how this could be done in a more optimized and better fashion.

utf8.idx could maybe be renamed to utf8.GetChar to match

### CODE REVIEW

**Comment by Donkie** [comment]
Another idea I had was to update the functions in the string library to by default have proper utf8 support?
Any function using string.len and string.sub is pretty toast in there when it comes to utf8.

Hint: PrintTable(string.Explode("", "abcdåäö"))

**Comment by meepdarknessmeep** [comment]
utf8 is a standard library in lua5.3 ported to glua (luajit). I doubt this will get pulled in its current state (being in the utf8 lib), I'd suggest another library or area or your own independent library.

**Comment by Kefta** [comment]
Then I guess we better remove all custom Garry's Mod functions inside default Lua libraries (string, math, debug) with that logic.

**Comment by meepdarknessmeep** [comment]
The thing is that proposals such as these have been removed in the past for the reason, not that I agree with it.

**Comment by Donkie** [comment]
@robotboy655 any reason this isn't being accepted?

**Comment by robotboy655** [comment]
Ahem, have you actually tested this?

image

Also I am not sure your utf8.sub (when it works) compares to usage like this:
```
local str = "1234567890abcdefghijklmnopr"
print( str:sub(4), str:sub(-4) )
```

**Comment by Donkie** [comment]
I've used it on my servers for years without any problems, however in a gamemode file so it might be some issue with this specific version, I'll check it out.

**Comment by Kefta** [comment]
You're in the utf8 module so you cannot index by ``utf8``. Call library functions as if they were globals.

**Comment by robotboy655** [comment]
Works now. 

> utf8.idx could maybe be renamed to utf8.GetChar to match
Perhaps it should be that way to draw parallels with string library

**Pull request merged**
