### PR TITLE
[TTT] Using table.IsEmpty

### PR DESCRIPTION
**Pull request by realpack**

### CODE REVIEW

**Comment by bigdogmat** [comment]
None of these are optimizations, just a different and probably slower way of checking if a sequential table is empty.

**Comment by thegrb93** [comment]
isEmpty is only good for replacing table.Count(tbl)==0

**Comment by ExtReMLapin** [comment]
If it was a few % difference i wouldn't complain here but clearly the isempty call is fucking slower than using the sequential table counter.

# :	0.074
isempty: 	2.8

**Comment by realpack** [comment]
I didn’t know that everything was so bad.

**Pull request closed without merging**
