### PR TITLE
Rework part of server list

### PR DESCRIPTION
**Pull request by meepdarknessmeep**
- Servers with ping <= 75 don't get penalized
- [LANG] tags in host names are now parsed into a flag icon and get more rank
- Server-is-full check is now properly performed with bots
- [L]isten server tags are now properly removed
- Gamemodes generate only one random, stopping new servers in gamemodes with 0 people from spazzing around

### CODE REVIEW

**Comment by uRandomAlex** [comment]
gr8 for pull #1337

**Comment by mcNuggets1** [comment]
I don't know what the flag change looks like?

**Comment by HandsomeMatt** [comment]
@mcNuggets1 it puts a flag before the server name if the server name contains [language] in the server name.

e.g: My TTT Server [es] would display `resource/localization/es-ES.png` before it.

If the language matches your local language, the server is ranked up more.

**Comment by meepdarknessmeep** [comment]
it actually only looks at the first language.length + 3 letters to check if it is "[es] " - but other than that matt is right

**Comment by robotboy655** [comment]
It looks like this:
!(http://i.imgur.com/nvlZTqR.png)[]

But it misses a lot of the tags

**Comment by meepdarknessmeep** [comment]
It uses the languages available to gmod only - if you add more language flags in the resource folder it will automatically add more tags.
otherwise servers with [GER] can just switch directly to [DE], or other things such as that.

Another problem I had with it (that we could fix with a resource file change) is that the spanish flag is from spain, not spain/mexico. We could probably have some of those flags blended together or something.

**Comment by Kefta** [comment]
Problem with that there are a lot of South American countries that also speak Spanish -- we ultimately can't fit everyone. We could separate Spanish and Castilian and have a Mexican and Spanish flag, respectively.

**Comment by meepdarknessmeep** [comment]
The problem is not having one for each country, it's for having the people know what language it is. I would suggest the English flag be changed to American/UK and the spanish one Mexico/Spain

**Comment by mcNuggets1** [comment]
Well, I don't like the flags.

**Comment by meepdarknessmeep** [comment]
Thanks, can you now give criticism about what part you don't like?

**Comment by mcNuggets1** [comment]
I just don't like the look and I am already used to searching for tags.

**Comment by meepdarknessmeep** [comment]
Did you even try the changes? You can still search for language tags...

What about the look makes you upset?

**Comment by mcNuggets1** [comment]
I just don't like how it looks like.

Making a new column for flags which could be sorted would be really cool, tho.

**Comment by Kronos9247** [comment]
It would be very usefull to have

**Comment by meepdarknessmeep** [comment]
um, whoops
data is gone

**Comment by meepdarknessmeep** [comment]
not like it was going to be pushed anyways

**Comment by Kefta** [comment]
Darn

**Pull request closed without merging**
