### PR TITLE
Updated Stack implementation

### PR DESCRIPTION
**Pull request by Kefta**
- Add ``table PopMulti(number[0, inf) Count = 1)``
- Moved all data to array indicies for faster access
- Pop now errors when given invalid args
- Pop now returns the last element it popped (solves https://github.com/Facepunch/garrysmod-requests/issues/217)
- Various optimisations, biggest being changing table.remove to direct element removal in Pop

### CODE REVIEW

**Comment by robotboy655** [comment]
Maybe `Push()` should return the position the new entry was put into, and I really don't like how you can remove multiple entries with `Pop()` but it will only return 1 removed entry regardless, but I am not sure what's what to do about it, or if anything should be done.

**Comment by Kefta** [comment]
How about adding a boolean parameter defaulting to false which will return a table popped values instead of just the top value?

**Comment by robotboy655** [comment]
That sounds extra hacky, ideally it should just return a table if it removed more than one element, but I am not sure how that affects ~ PERF ~

**Comment by Kefta** [comment]
That's what I was also concerned over. Maybe two separate functions, Pop and PopTable? PopTable will always return a table no matter how many elements were popped.

**Comment by robotboy655** [comment]
Perhaps something like PopMultiple or PopMulti? PopTable sounds like you are popping the first `table` type or something.

**Comment by Kefta** [comment]
Added ``table Stack:PopMulti(unsigned Count)``; I chose Multi over Multiple for consistency with ``Entity:PhysicsInitMultiConvex`` and ``DModelSelectMulti``. The function will always return a table, even with ``PopMulti(0)``.

**Pull request merged**
