### PR TITLE
Add DButton:SetMaterial & DImageButton:SetMaterial

### PR DESCRIPTION
**Pull request by aStonedPenguin**
Quality of life change.

### CODE REVIEW

**Comment by GitSparTV** [comment]
Add binding for DImageButton as well.
It doesn't have SetMaterial as well

**Comment by GitSparTV** [comment]
Epic

**Comment by robotboy655** [comment]
You can just do `PANEL.SetMaterial = PANEL.SetImage` for the DButton, but do we really need a 3rd function to do the same thing?

**Comment by aStonedPenguin** [comment]
[DButton:SetImage](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/vgui/dbutton.lua#L32) calls [DImage:SetImage](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/vgui/dimage.lua#L91) which only accepts a string.

DButton:SetImage could be made to call DImage:SetMaterial but if SetMaterial and SetImage are different functions in DImage shouldn't they be different in all for cohesiveness?

**Comment by robotboy655** [comment]
Missed that difference, my bad.

**Pull request merged**
