### PR TITLE
Ammo lib update

### PR DESCRIPTION
**Pull request by Kefta**
- Bad tbl.name no longer silently fails.
- Made ammo names case-insensitive.

### CODE REVIEW

**Comment by robotboy655** [comment]
This needs to be updated since one of the recent updates added its own game.GetAmmoType

**Comment by Kefta** [comment]
Removed GetAmmoType from this PR.

**Comment by robotboy655** [comment]
Is there any reason for `AmmoNames` to exist and to carry the ammo table which is never used?
You may argue its ~ faster ~ to check if ammo type is already registered but ` game.AddAmmoType` is not exactly something that is called often for this to matter.

**Comment by Kefta** [comment]
Done

**Pull request merged**
