### PR TITLE
Add function "draw.Box"

### PR DESCRIPTION
**Pull request by JarosLucky**
stop using draw.Round box to create a box. without check the `Round size is <= 0`

### CODE REVIEW

**Comment by neico** [comment]
Could have used
```lua
function Box( x, y, w, h, color )
    RoundedBox( 0, x, y, w, h, color )
end
```
but that's actually one extra function call compared to yours, but who is counting these anyway~

**Comment by Kefta** [comment]
@neico Lua

**Comment by JarosLucky** [comment]
@neico Your suggestion is a function that uses a function uses a fuction for check to draw a box. This just create a box.

**Comment by JarosLucky** [comment]
@Kefta what do not you like about my offer?

**Comment by end360** [comment]
Saves 1 comparison, very important.

**Comment by ExtReMLapin** [comment]
certified darkrp coder

**Comment by Etothepowerof26** [comment]
to be honest this is very useless

**Pull request closed without merging**
