### PR TITLE
Update getmaps.lua

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by robotboy655** [comment]
No thank you. Gamemode maps get their own categories when their gamemode is installed, we don't want to be hardcoding all possible gamemode variations into getmaps.lua

What exists there is there because those gamemodes didn't come from GMod itself or are from the mountable games.

**Comment by Kefta** [comment]
If that's the case, all the custom gamemodes at the bottom should have their categories removed. This is inconsistent.

**Comment by Kefta** [comment]
Though I think they should just all be allowed - who has all of these gamemodes installed?

**Comment by robotboy655** [comment]
Huh, how did some of those get in there? 

But honestly, do we really want to start aggregating gamemodes there like that? Why not just starting hardcoding gamemode names for everything like in the server list. At what point do we just ship all gamemodes with the game?

**Comment by Kefta** [comment]
I think harcoding them in the map categories is fine since the prefixes themselves are hardcoded: ``scp_`` will never be anything but ``Secure. Contain. Protect.``, ``dr_`` will never be anything but ``Deathrun``, etc. It's for user convenience and it's updated like once a year at most.

**Comment by robotboy655** [comment]
I don't mind having very popular things there - RP, deathrun, surf, bhop, etc, but I don't think custom obscure things have a place there.

**Pull request closed without merging**
